### ISSUE TITLE
OpenTracing interceptor should be able to ignore certain failures

### ISSUE THREAD

**Issue by tylercunnion** [temporalio/sdk-java#1012]
**Is your feature request related to a problem? Please describe.**
Our workflow involves a lot of polling external services, following the pattern whereby we check for a result and throw an exception if it's not ready yet. As a result, we produce a lot of OpenTracing spans with errors that are actually normal, expected behavior. We also show an artificially inflated error % as a result.

**Describe the solution you'd like**
I'd like to be able to exclude certain exception types from being logged as errors in the OpenTracing interceptor.

**Describe alternatives you've considered**
I'm not sure if there's another use case for this beside the specific one I'm dealing with, so if it doesn't seem generally-applicable enough I could always just implement a new interceptor for this project's use. And of course the optimal way would be to simply not have to poll (but setting up the external services to send signals is outside of our current scope).

**Comment by Spikhalskiy** [comment]
We can add a configurable `java.util.function.Predicate` that accepts an exception into OpenTracingOptions#isErrorPredicate. Default implementation should just return `true`.

@tylercunnion will you be interested in contributing? It should be a pretty local change into temporal-opentracing.
