### ISSUE TITLE
Health check between service + temporal servers

### ISSUE THREAD

**Issue by AngerM-DD** [temporalio/sdk-java#102]
**Is your feature request related to a problem? Please describe.**
With cadence we have seen issues where clients lose their connection and are unable to reconnect to the cadence servers

**Describe the solution you'd like**
A health checking mechanism that allows me to check whether the workers/factory have a healthy connection. This would allow us to check something like `factory.isHealthy()` in a k8s health check endpoint and restart the worker services if necessary

**Describe alternatives you've considered**
None.

**Additional context**
We built this into the cadence java client by forking it and using the TChannel meta health check that cadence looks to already implement.

**Comment by bbottema** [comment]
Yep, we're spinning up a Temporal container to use in our cucumber tests, but currently have no way of knowing if the server is up.

**Comment by vkoby** [comment]
@bbottema does this pull request address your issue?
