### ISSUE TITLE
Missing WorkflowExecutionUtils.describeWorkflowInstance()

### ISSUE THREAD

**Issue by SilverSheep** [temporalio/sdk-java#1028]
I want to upgrade from temporalio/sdk-java 1.1.0 to 1.8.0, but I've encountered a problem. New version is missing `WorkflowExecutionUtils.describeWorkflowInstance()` method. As I've checked - it was still available in 1.3.1, but during refactoring of `WorkflowExecutionUtils` in 1.4.0 it was removed. 

Why was it removed? Is there an alternative to get workflow execution status?

## Expected Behavior
WorkflowExecutionUtils.describeWorkflowInstance() is available

## Actual Behavior
WorkflowExecutionUtils.describeWorkflowInstance() is missing 

## Steps to Reproduce the Problem

  1. Use version 1.1.0 of temporalio/sdk-java
  1. Use WorkflowExecutionUtils.describeWorkflowInstance() somewhere in your code
  1. Update temporalio/sdk-java to version 1.8.0
  1. Try to compile your code

## Specifications

  - Version: 1.8.0
  - Platform: Linux

**Comment by Spikhalskiy** [comment]
`io.temporal.internal.common.WorkflowExecutionUtils` is an internal class and you shouldn't be using it at the first place. The method was removed because JavaSDK doesn't need it anymore.
