### ISSUE TITLE
Add describeWorkflowExecution

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1036]
`describeWorkflowExecution` is an API that is used regularly for a large range of checks by the users, Temporal SDK should expose it as a part of the official WorkflowStub API.

Typical usages of `describeWorkflowExecutions` include checking the status of a workflow.

Related: #1028 https://github.com/temporalio/sdk-features/issues/17

**Comment by cretz** [comment]
Also related to https://github.com/temporalio/sdk-features/issues/17.

Whatever this is named, I think the result just needs to make sure it's wrapped in a friendly Java class that exposes the status and the underlying gRPC response. (can add more than just status though if you want)

**Comment by Quinn-With-Two-Ns** [comment]
duplicate of https://github.com/temporalio/sdk-java/issues/2265
