### ISSUE TITLE
Remote Data Encoder

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1044]
Provide a framework for serving and consuming data encoding via HTTP across all our SDKs. 

1. Frees users to write their encryption code in whichever of our SDK-supported languages they prefer.
2. Allows users to restrict access to their encryption keys or KMS API usage to only the remote decoder process rather than developer workstations.
3. Allows `tctl` to encode payloads for `tctl workflow start`. Note: This will not work for any encoders which require workflow context. Fixing this is outside the scope of the MVP

[Remote_Data_Encoder_protocol.pdf](https://github.com/temporalio/sdk-java/files/8100346/Remote_Data_Encoder_protocol.pdf)

GoSDK reference implementation: https://github.com/temporalio/sdk-go/pull/717 https://github.com/temporalio/sdk-go/pull/733

**Comment by robholland** [comment]
Please note protocol update (Payloads vs Payload): https://github.com/temporalio/sdk-go/pull/733

**Comment by robholland** [comment]
The linked PDF is correct and matches https://github.com/temporalio/sdk-go/pull/733

**Comment by robholland** [comment]
Go and TS SDKs both have nice APIs for this now, would be great to get this in Java too.

**Comment by Spikhalskiy** [comment]
Not really our preferred or advised method to do that. It's more of a workaround if the standard approach to data converters is not applicable. Is there a specific client and usecase asking?

**Comment by Spikhalskiy** [comment]
The majority of users should stick to standard data converters for a variety of reasons as long as they could. And security is one of them.

**Comment by StevenLangbroek** [comment]
Hey! Temporal Cloud customer here, we'd love for the Java SDK to have parity with the other SDKs in this specific area.
