### ISSUE TITLE
Bug when building WorkerOptions

### ISSUE THREAD

**Issue by javiercanillas** [temporalio/sdk-java#1080]
## Expected Behavior
Have different values of `maxConcurrentActivityExecutionSize` and `maxConcurrentLocalActivityExecutionSize` when configuring `WorkerOptions`.

## Actual Behavior
`maxConcurrentLocalActivityExecutionSize` is configured using `maxConcurrentActivityExecutionSize` when building the object:

Taken from `WorkerOptions.Builder.build()` [here](https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java#L288):
```java
    public WorkerOptions build() {
      return new WorkerOptions(
          maxWorkerActivitiesPerSecond,
          maxConcurrentActivityExecutionSize,
          maxConcurrentWorkflowTaskExecutionSize,
          maxConcurrentActivityExecutionSize,
          maxTaskQueueActivitiesPerSecond,
          workflowPollThreadCount,
          activityPollThreadCount,
          localActivityWorkerOnly,
          defaultDeadlockDetectionTimeout);
    }
```
It should be:

```java
    public WorkerOptions build() {
      return new WorkerOptions(
          maxWorkerActivitiesPerSecond,
          maxConcurrentActivityExecutionSize,
          maxConcurrentWorkflowTaskExecutionSize,
          maxConcurrentLocalActivityExecutionSize,
          maxTaskQueueActivitiesPerSecond,
          workflowPollThreadCount,
          activityPollThreadCount,
          localActivityWorkerOnly,
          defaultDeadlockDetectionTimeout);
    }
```

See the change on the 4th argument.

## Steps to Reproduce the Problem

  1. Create an `WorkerOptions.Builder` object.
  2. Set the attribute `maxConcurrentActivityExecutionSize` with value 10
  3. Set the attribute `maxConcurrentLocalActivityExecutionSize` with value 200
  4. Call `build` over the Builder instance
  5. Check that the built object `WorkerOptions` will have both `maxConcurrentActivityExecutionSize` and `maxConcurrentLocalActivityExecutionSize` with value 10.

## Specifications
  - Version: temporal-sdk-1.3.1
  - Platform: java

**Comment by Spikhalskiy** [comment]
Confirm, thanks for the report!

Please use `validateAndBuildWithDefaults` as a temporary workaround if you need one. This is our main method to build Options instances right now.
