### ISSUE TITLE
Incompatible protobuf-java-util library usage

### ISSUE THREAD

**Issue by pmh92** [temporalio/sdk-java#1097]
## Expected Behavior
WorkerFactory instance is created properly

## Actual Behavior
The following exception is thrown:
`java.lang.NoSuchMethodError: 'boolean com.google.protobuf.GeneratedMessageV3.isStringEmpty(java.lang.Object)'`

## Steps to Reproduce the Problem

  1. Add io.temporal:temporal-sdk:1.8.1 to pom.xml
  2. Try to instantiate a WorkerFactory
  
## Specifications

  - Version: 1.8.1
  - Platform: macOS

As in the `io.temporal:temporal-serviceclient` pom.xml the version is labelled as follows:
```
<dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java-util</artifactId>
      <version>[3.10.0,)</version>
      <scope>compile</scope>
      ...
</dependency> 
```
I found out that there is a new version of `com.google.protobuf:protobuf-java-util` with version **4.0.0-rc-2**. This new version is loaded first, which seems to be incompatible with `io.grpc:grpc-services:1.44.1`.

I fixed this by specifying version **3.19.4** of `com.google.protobuf:protobuf-java-util` in my application's pom.xml

```
<dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java-util</artifactId>
      <version>3.19.4</version>
</dependency>
```

**Comment by Spikhalskiy** [comment]
It's already fixed in master and will be included in the next release.
Duplicates of https://github.com/temporalio/sdk-java/issues/1085 and https://github.com/temporalio/sdk-java/issues/1091
