### ISSUE TITLE
Permissions Error for Links Followed via javadoc.io Search

### ISSUE THREAD

**Issue by tomwheeler** [temporalio/sdk-java#1104]
## Expected Behavior

According to the sidebar on [this page](https://docs.temporal.io/docs/java/), Temporal's Java SDK documentation is published on javadoc.io, a site that allows one to browse, search, and read API documentation.

## Actual Behavior

Although you can successfully navigate to any page by clicking [links shown on the main API documentation page](https://www.javadoc.io/doc/io.temporal/temporal-sdk/latest/index.html), navigating to any page in the search results seems to produce an AccessDenied error. I suspect this might be related to the `/undefined/` path segment added to the URL when following search results, as this path segment does not appear in the URL otherwise.

## Steps to Reproduce the Problem

  1. Browse to [the latest API doc for the Temporal Java SDK](https://www.javadoc.io/doc/io.temporal/temporal-sdk/latest/index.html)
  2. Click the **Search** box near the upper-right corner
  3. Enter **`RetryOptions`** in the box (though any class or method would also demonstrate the problem)
  4. Click any of the matching results
  5. Observe the AccessDenied error similar to the screenshot below:

![image](https://user-images.githubusercontent.com/2183904/160472950-39be4655-9ed4-4656-a22f-19421aeb511d.png)

## Specifications

  - Version: Firefox, version 91.7.1esr (64-bit), but likely not browser-specific
  - Platform: Mac OS Monterey 12.2.1 (21D62), but likely not platform-specific

**Comment by Spikhalskiy** [comment]
Fixed by #1078
