### ISSUE TITLE
Workflow metadata resolution code doesn't respect generics specified down the hierarchy

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1106]
## Expected Behavior

```
@WorkflowInterface
public interface ReportingWorkflow extends TemporalWorkflow<ReportQueriesResponse> {
  @WorkflowMethod
  ReportQueriesResponse runReport(ReportQueries reportQueries);
}

public interface TemporalWorkflow<T> extends TemporalRunnable {
  @QueryMethod
  T getResults();
}
```

Temporal JavaSDK should be able to understand that `ReportingWorkflow#getResults` returns ReportQueriesResponse and use this class as a target in data conversion.

## Actual Behavior

Data Converters try to decode query results into `Object`.

## Notes

Worth checking the same problem for Activity Metadata resolution. 

## Specifications

  - Version: 1.8.x

**Comment by mfateev** [comment]
I don't think this is a bug. Given that Java erases generics information at runtime, it is impossible to implement.

**Comment by cretz** [comment]
> it is impossible to implement.

True, but there are utilities if we ever want to have user-specified generic values (e.g. maybe a default method that returns https://guava.dev/releases/21.0/api/docs/com/google/common/reflect/TypeToken.html for `T`)

But what I would recommend is to disallow annotations on generic methods. If Temporal needs to know concrete types, it should be an error not to be able to reflectively obtain them. So in the pasted sample, they'd need to provide an annotation on the concrete interface override instead.

**Comment by Spikhalskiy** [comment]
> Given that Java erases generics information at runtime, it is impossible to implement.

It's not exactly true. Java erases generic information for dynamically created instances of gentrified classes. But Java do preserve information about generic typed for defined standalone classes. Basically, if you have `class A extends/implements B<C>` - type of C is preserved.
So, it's possible and it's a bug.

**Comment by cretz** [comment]
You're going to have to have really complicated rules about how to derive `C` in complicated inheritance scenarios. And what if they never provide a type parameter? in an inherited interface? Or what if they do `? extends List<String>` or something. Or additional type constraints in multiple levels? Or if they have an impl that uses a more specific generic value than the interface?

I think this is a can of worms that you can only half support. I can give lots of confusing scenarios. To me the most straightforward answer is "you cannot define Temporal attributes on generic items". It's harmless to ask someone to have a concrete override for use by stubs and other items.

**Comment by Spikhalskiy** [comment]
> I think this is a can of worms that you can only half support.
That's fine. Most things that user need is a very straightforward 1-1 unbounded resolution we 100% can and should support.

An implementer of this feature should think about scenarios and may ban some specific scenarios and throw an exception if something is too complicated to resolve like it's already done now we a diamond inheritance.

What most people want from this feature of supporting generics is totally doable and non-ambiguous.

**Comment by cretz** [comment]
```java
@WorkflowInterface
public interface ReportingWorkflow<T extends ReportQueriesResponse> extends TemporalRunnable {
  @QueryMethod
  T getResults();
}
```

If I register this interface, will you support this use case?
