### ISSUE TITLE
Implement temporal.api.workflowservice.v1.WorkflowService/DescribeNamespace in test-server

### ISSUE THREAD

**Issue by seregazhuk** [temporalio/sdk-java#1158]
To start using test-sever in PHP-SDK we need the following functionality.

**Comment by Spikhalskiy** [comment]
Other SDK successfully use test server without this functionality. If it's a prerequisite for using test server in PHP SDK - that's what should be fixed first.

**Comment by rustatian** [comment]
> Other SDK successfully use test server without this functionality. If it's currently a prerequisite for using test server in PHP SDK, it shouldn't be. SDKs themselves never call describeNamespace, PHP shouldn't be different.

Hey @Spikhalskiy, Could you please point me to a doc or manual with a testing-server limitation? It would be great to see what API it doesn't support.

**Comment by Spikhalskiy** [comment]
This class: https://github.com/temporalio/sdk-java/blob/1816ad2499b8e98a20d158a8f0a4c64bb41a9a09/temporal-test-server/src/main/java/io/temporal/internal/testservice/TestWorkflowService.java
implements WorkflowService, all methods that are not overridden will throw an UNIMPLEMENTED exception.

Currently, it's
```
  registerNamespace
  describeNamespace
  listNamespaces
  updateNamespace
  deprecateNamespace
  getWorkflowExecutionHistoryReverse
  resetWorkflowExecution
  listWorkflowExecutions
  listArchivedWorkflowExecutions
  scanWorkflowExecutions
  countWorkflowExecutions
  getSearchAttributes
  resetStickyTaskQueue
  describeTaskQueue
  getClusterInfo
  getSystemInfo
  listTaskQueuePartitions
```

Some notes:
registerNamespace is not needed for Test Server, you can just use any namespace name without registering with it
resetStickyTaskQueue probably should be implemented in a trivial way and just return silently without an exception. All SDKs just ignore any exception from the sticky queue reset, because it's not too important.

**Comment by rustatian** [comment]
@Spikhalskiy Great, thank you for the help.

However, this is not a PHP-SDK error, as I figured out.
I have created a simple worker in go-sdk (I'm not a Java dev, so forgive me for the snippet in Go), without any activities or workflows registered. Here is the sample:
```go
package main

import (
	"log"

	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/worker"
)

func main() {
	// The client and worker are heavyweight objects that should be created once per process.
	c, err := client.NewClient(client.Options{
		HostPort: client.DefaultHostPort,
	})
	if err != nil {
		log.Fatalln("Unable to create client", err)
	}
	defer c.Close()

	w := worker.New(c, "greetings", worker.Options{})

	err = w.Run(worker.InterruptCh()) <-------- ERROR is here
	if err != nil {
		log.Fatalln("Unable to start worker", err)
	}
}
```

If you run this code snippet with a test-server, you'll get an error: `2022/04/20 18:16:05 Unable to start worker Method temporal.api.workflowservice.v1.WorkflowService/DescribeNamespace is unimplemented`

**Comment by Spikhalskiy** [comment]
You are right. It was added to Go client in this issue: https://github.com/uber-go/cadence-client/pull/196 
It's actually a discrepancy on our side, we should either remove it from Go or add it to other SDKs. Java and Typescript don't do it right now.
But it looks like we should implement some stub describeNamespace in the test server just for the sake of compatibility with older versions of Go SDK.

**Comment by rustatian** [comment]
Got u, thanks 🤝 Looking forward to the solution 👍🏻
