### ISSUE TITLE
WorkflowStub.getResult and getResultAsync do not throw TimeoutException

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1177]
String result = workflow.getResult(X, TimeUnit.SECONDS, String.class);

If this call times out (workflow does not complete before X seconds):

1. if X < 10
You get GrpcSyncRetryer -> DEADLINE_EXCEEDED: deadline exceeded after Xs
and can catch WorkflowServiceException

3. if X >=10
You get two GrpcSyncRetryer logs:
a) DEADLINE_EXCEEDED: context deadline exceeded
b) Failure, out of retries
and can catch WorkflowServiceException

Same happens with getResultAsync

The only way to catch TimeoutException is if you use getResultAsync and put the timeout on Future.get, for example:

     CompletableFuture<String> future = workflow.getResultAsync(String.class);
     String result = future.get(X, TimeUnit.SECONDS);

Note that even in this case if X >=10 you do get DEADLINE_EXCEEDED in worker logs from GrpcAsyncRetryer

**Comment by Spikhalskiy** [comment]
#1203 should be done before this to cleanup the long poll implementation
