### ISSUE TITLE
Search attributes are not carried forward on ContinueAsNew

### ISSUE THREAD

**Issue by robzienert** [temporalio/sdk-java#1200]
## Expected Behavior

Search attributes to be carried-forward during `Workflow.continueAsNew()`

## Actual Behavior

Continued-as-new workflows are missing the search attributes from the original run.

## Steps to Reproduce the Problem

  1. Create a workflow with search attributes
  1. Call `continueAsNew`
  1. Verify via tctl that search attributes are missing from new run ID.

## Specifications

  - Version: 1.10.0
  - Platform: 1.15.2

**Comment by Spikhalskiy** [comment]
Use  ContinueAsNewOptions.Builder.setSearchAttributes(searchAttributes) to pass search attributes into `continueAsNew`.

**Comment by patte** [comment]
> Use `ContinueAsNewOptions.Builder#setSearchAttributes` to pass search attributes into `continueAsNew` for now.

Is there a similar possibility in the python SDK for `retry_policy`? I don't see `retry_policy` as a param in `continue_as_new`.

**Comment by Spikhalskiy** [comment]
@patte Please post as a question in `#python-sdk` channel of our [Community Slack](https://temporal.io/community) or as a feature request in https://github.com/temporalio/sdk-python/issues
