### ISSUE TITLE
Consider making std-out of Test Server more useful.

### ISSUE THREAD

**Issue by macrogreg** [temporalio/sdk-java#1222]
When starting the Test Server (on Windows) without arguments, it displays this:

```
PS dir> .\temporal-test-server.exe
Usage: <command> <port> <flags>
Flags:
--enable-time-skipping - to enable time skipping on start
```

It is intuitively clear what "port" means, and "flags" is explained.
I have no idea what "command" means. and I cannot find any docs. Can the above usage display please explain it?

Also, both the _command_ and the _flags_ appear to be optional, as the following starts the server:

```
PS dir> .\temporal-test-server.exe 7233
```

Could we please indicate that on the usage display too?

Finally, once the above command with the port is issued, the server just starts. Nothing is displayed. Some brief message that the server is not running, listening on the specified port and is ready to handle requests would be very useful. :)

Thanks for considering those improvements. :)

**Comment by Spikhalskiy** [comment]
<command> is "./temporal-test-server" itself. It's, well, mandatory.

> Also, both the command and the flags appear to be optional, as the following starts the server.

Flags are usually optional.
