### ISSUE TITLE
Multiple workers reporting workflow gauges

### ISSUE THREAD

**Issue by robzienert** [temporalio/sdk-java#1260]
## Expected Behavior
I would expect that when using `Workflow.getMetricScope().gauge("foo")` within a long-lived workflow execution, only a single worker would report this metric.

## Actual Behavior
If the workflow that emits a gauge is scheduled across multiple nodes, then each node is emitting a gauge value but all nodes except the latest one to report gauge are continuing to report outdated gauge values.

It's possible that this is an issue in [spectator](https://github.com/Netflix/spectator). If that is indeed the case, it would be great if the Java SDK could add a listener interface around workflow scheduling (e.g. being able to to listen for when workflows stop running on a worker) so we can evict metric gauges from the registry.

## Steps to Reproduce the Problem

  1. Define a gauge, set a value in a `Workflow.await`
  1. Reschedule the workflow to a different worker

## Specifications

  - Version: 1.12.0
  - Platform: 1.16.2

**Comment by Spikhalskiy** [comment]
I don't think t is related to JavaSDK. We don't really implement metrics. The gauge that you use this way is just a micrometer gauge.

> If the workflow that emits a gauge is scheduled across multiple nodes, then each node is emitting a gauge value but all nodes except the latest one to report gauge are continuing to report outdated gauge values.

This does sound like correct behavior. Each of these nodes has its own gauge and it's reporting its last value for the node.

I never heard about global gauges that synchronize gauge value across nodes.

**Comment by Spikhalskiy** [comment]
`Workflow.getMetricScope().gauge()` returns a gauge of a current WORKER. The described behavior is aligned with the normal behavior of a host metric's gauge.
`Workflow.getMetricScope().gauge()` doesn't return a gauge isolated to a specific workflow. This abstraction doesn't exist and it's not a goal of this method.

**Comment by Spikhalskiy** [comment]
@robzienert feel free to reach out to me on the community Slack to discuss it if you disagree and it looks off.
