### ISSUE TITLE
Local Activity asynchronously started at the end of the workflow implementation leads to failure

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1281]
## Expected Behavior

```
    @Override
    public void wofklowMethod() {
      Async.procedure(activity::execute);
    }
```

An activity scheduled at the end of the workflow code asynchronously without waiting on the promise should be ignored.
Alternatively, it may be executed. 
Such a code shouldn't block workflow completion, it's not an invalid workflow implementation.

## Actual Behavior

It leads to
`io.grpc.StatusRuntimeException: NOT_FOUND: workflow execution already completed` exception on worker with workflow never completing.

## Steps to Reproduce the Problem
Unit test: https://github.com/Spikhalskiy/java-sdk/commit/718fe8e794a50188c639e79a6ee47576960ae353

**Comment by bergundy** [comment]
@Spikhalskiy please add to sdk features. Not 100% sure we put it there

**Comment by Spikhalskiy** [comment]
Related to #1722

**Comment by Quinn-With-Two-Ns** [comment]
https://github.com/temporalio/sdk-java/commit/8b3be3bb521f7ab62b7d384ee417d053286a95d5
