### ISSUE TITLE
Provide WorkflowInfo#getHistoryLength()

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1300]
**Is your feature request related to a problem? Please describe.**
Users should be able to have a more direct way to check if it's time to call continue-as-new than guessing how many events their code produces and counting the loops.

**Describe the solution you'd like**
`WorkflowInfo#getHistoryLength()` should be exposed that would allow a direct comparison with a threshold length of the history

**Context**
The implementor needs to be careful with the deterministic behavior of this value, as it has to be exactly the same during a replay. Also, it should be noted that custom metrics and determining if continue-as-new is needed are probably the only valid usages of this method in user code.

**Comment by cretz** [comment]
I think we should call this `getHistoryLength()` since there will be a way to get byte size of history soon

**Comment by gtorrance-bw** [comment]
For what it's worth, I anticipate needing a feature like this, too. Hope it gets prioritized in the near future. Thanks.
