### ISSUE TITLE
Use client OpenTracing/OpenTelemetry spans for signal and queries

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1306]
## Expected Behavior

Signal and query handlers and threads inherit the client span as a parent span and form a solid spans chain with spans of the clients calling a signal or a query method.

## Actual Behavior

Historically Temporal server signal and query APIs didn't have headers and it wasn't possible to transfer additional payloads like spanId from the caller. Signal and queries currently don't inherit the client's span.

**Comment by deepakjeena** [comment]
Hi Team, any update on this

**Comment by Quinn-With-Two-Ns** [comment]
Closed by https://github.com/temporalio/sdk-java/pull/1819
