### ISSUE TITLE
An api to know if the current Thread is running under Workflow Context

### ISSUE THREAD

**Issue by manas-tripathy** [temporalio/sdk-java#1321]
**Expected Behavior**
Introduce a new API Workflow.isWorkflowThread() to know if the current thread is under WorkflowContext

**Actual Behavior**
Workflow.getInfo() is throwing "Called from non workflow or workflow callback thread" when called from a  Non Workflow Thread.
Please refer [community thread](https://community.temporal.io/t/removing-thread-locals-after-context-propagation/5361) for more details.

**Specifications**
Version: 1.11.0
Platform: java-sdk

**Comment by Spikhalskiy** [comment]
Already exists as `WorkflowUnsafe.isWorkflowThread`
