### ISSUE TITLE
Seeing SIGSEGV error while calling WorkflowServiceStubs.newServiceStub

### ISSUE THREAD

**Issue by shubhati** [temporalio/sdk-java#1332]
While running workflow worker in kubernetes pod, the below error is seen 
```
 A fatal error has been detected by the Java Runtime Environment:

  SIGSEGV (0xb) at pc=0x0000000000003fd6, pid=7, tid=0x00007fc7329e8ae8

 JRE version: OpenJDK Runtime Environment (8.0_275-b01) (build 1.8.0_275-b01)
 Java VM: OpenJDK 64-Bit Server VM (25.275-b01 mixed mode linux-amd64 compressed oops)
 Derivative: IcedTea 3.17.1
 Distribution: Custom build (Tue Feb 16 18:40:09 UTC 2021)
 Problematic frame:
 C  0x0000000000003fd6

 Core dump written. Default location: //core or core.7

 An error report file with more information is saved as:
 //hs_err_pid7.log
```
 If you would like to submit a bug report, please include
 instructions on how to reproduce the bug and visit:
   https://icedtea.classpath.org/bugzilla 

the hs_err_pid7.log file is uploaded with this issue. The error occurs when newservicestub method is called to start the workflow worker. The code is below
```
PrometheusMeterRegistry registry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
        StatsReporter reporter = new MicrometerClientStatsReporter(registry);
        Scope scope = new RootScopeBuilder()
                .reporter(reporter)
                .reportEvery(com.uber.m3.util.Duration.ofSeconds(10));
        HttpServer scrapeEndpoint = startPrometheusScrapeEndpoint(registry, 8002);
        Runtime.getRuntime().addShutdownHook(new Thread(() -> scrapeEndpoint.stop(1)));
        WorkflowServiceStubsOptions options = WorkflowServiceStubsOptions.newBuilder()
                .setMetricsScope(scope)
                .setTarget("temporaltest-frontend.temporal.svc.cluster.local:7233")
                .build();
        WorkflowServiceStubs stubs = WorkflowServiceStubs.newServiceStubs(options);
```

Not able to proceed because of this error. please help me out
[hs_err_pid7.log](https://github.com/temporalio/sdk-java/files/9222049/hs_err_pid7.log)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version: sdk version 1.12.0
  - Platform: linux machine kubernetes pod

**Comment by Spikhalskiy** [comment]
What specific Linux distribution is used?

**Comment by shubhati** [comment]
Linux version: `Linux version 5.4.196-108.356.amzn2.x86_64 (mockbuild@ip) (gcc version 7.3.1 20180712 (Red Hat 7.3.1-13) (GCC)) #1 SMP Thu May 26 12:49:47 UTC 2022`

**Comment by Spikhalskiy** [comment]
@shubhati I don't think the dump attached to this issue is Red Hat Linux, because:

```
OS:NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.8.2
PRETTY_NAME="Alpine Linux v3.8"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
```

So, this crash happened on Alpine.

**Comment by Spikhalskiy** [comment]
Please reference https://github.com/grpc/grpc-java/issues/8751 for a solution.
Basically, you have three options:
1. `-Dio.grpc.netty.shaded.io.netty.transport.noNative=true`. I don't recommend this option as it will cause performance implications, but it may be a temporary workaround.
2. LD_PRELOAD fix: https://github.com/grpc/grpc-java/issues/8751#issuecomment-998199569
3. Wait for the next release of JavaSDK that will bring updated grpc-java which brings updated netty with a [change](https://github.com/netty/netty/pull/12313) that MAY help this issue.

Closing as not a JavaSDK bug.

**Comment by shubhati** [comment]
Strange, the output was the content of `/proc/version` file of the pod's VM. But surely will try the solutions suggested. Thanks a lot for quick help @Spikhalskiy

**Comment by deltamualpha** [comment]
I ran into this issue with alpine and 1.14.0 of the SDK; the same version of alpine combined with 1.15.0 did not exhibit the crash after upgrade.

**Comment by Spikhalskiy** [comment]
Thanks, @deltamualpha for the confirmation that it's indeed fixed.
