### ISSUE TITLE
Pass real WorkflowId for full replay exposed to users in Worker#replayWorkflowExecution

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1378]
## Actual Behavior

[Currently](https://github.com/temporalio/sdk-java/blob/37a0e463fae2312882b5c946f423a0dbf85f9666/temporal-sdk/src/main/java/io/temporal/internal/worker/QueryReplayHelper.java#L76) during a full replay that is explicitly exposed to users using `Worker#replayWorkflowExecution`, JavaSDK supplies [fake](https://github.com/temporalio/sdk-java/blob/37a0e463fae2312882b5c946f423a0dbf85f9666/temporal-sdk/src/main/java/io/temporal/internal/common/WorkflowExecutionHistory.java#L115) WorkflowId which can break determinism if workflow code depends on these values.

## Expected Behavior

Actual values from the history should be taken and supplied to the Workflow in WorkflowInfo during replay.

## Additional context

https://community.temporal.io/t/recommended-approach-to-testing-backwards-compatibility/5511

Good catch from Max that the same shouldn't apply to RunID, because usage of runId in workflow code is non-deterministic (think of reset)

**Comment by mfateev** [comment]
The workflow code must not depend on runId as reset operation changes it.

**Comment by Spikhalskiy** [comment]
@mfateev Fair, good catch on runId. I will add this comment on WorkflowInfo#getRunId javadoc, because I don't think we state this unobvious fact anywhere.

**Comment by bergundy** [comment]
We should consider putting run_id in unsafe (might be too late though), the only issue is that the current run_id isn't stored in history so we can't provide it to the replayer, we only have original_run_id in WorkflowExecutionStarted which is the closest thing.

**Comment by mfateev** [comment]
There is [originalRunId](https://github.com/temporalio/api/blob/79e9495c8f2c2518bb29cb72056c796b5b9fc26a/temporal/api/history/v1/message.proto#L77) that is preserved on reset.

**Comment by Spikhalskiy** [comment]
Addressed by #1497
