### ISSUE TITLE
Jackson configuration is cumbersome

### ISSUE THREAD

**Issue by Bennett-Lynch** [temporalio/sdk-java#1387]
I need to register [jackson-module-kotlin](https://mvnrepository.com/artifact/com.fasterxml.jackson.module/jackson-module-kotlin) with the Temporal SDK in order to support Kotlin data classes. As far as Jackson goes, this is accomplished with a fairly trivial modification to the `ObjectMapper`. However, the Temporal SDK currently makes it very cumbersome to get a hook onto that reference.

While it's possible to declare your entirely own `DataConverter`, it requires replicating a large portion of the default Temporal configuration. E.g., here is the code I would need to write if I just wanted to make one simple Jackson modification:

```
// Replicate the default Jackson configuration
val mapper = ObjectMapper()
mapper.configure(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, false)
mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
mapper.registerModule(JavaTimeModule())
mapper.registerModule(Jdk8Module())
mapper.setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY)

// Enable my Jackson customization
mapper.registerKotlinModule()

// Replicate the default payload converters (in order) while overriding JacksonJsonPayloadConverter
val dataConverter = DefaultDataConverter(
    NullPayloadConverter(),
    ByteArrayPayloadConverter(),
    ProtobufJsonPayloadConverter(),
    ProtobufPayloadConverter(),
    JacksonJsonPayloadConverter(mapper)
)

// Register the global default
GlobalDataConverter.register(dataConverter)
```

This is a lot of boilerplate and prone to falling out of sync with the defaults that we're copy/pasting.

Alternatively, I can use reflection to modify the `ObjectMapper` that is already registered globally. E.g.,

```
val jacksonConverter = DefaultDataConverter.STANDARD_PAYLOAD_CONVERTERS.first { it is JacksonJsonPayloadConverter }
val mapperField = JacksonJsonPayloadConverter::class.java.getDeclaredField("mapper")
mapperField.isAccessible = true
val mapper = mapperField.get(jacksonConverter) as ObjectMapper
mapper.registerKotlinModule()
```

This is of course hacky, but I actually prefer it since I know my settings won't drift out of sync from Temporal's default configuration, and I'll get an explicit failure if something breaks with the reflection.

It would be nice if it was simpler and easier to be able to customize the Jackson-level configuration. Some potential solutions:

1. Similar to exposing a global `DataConverter`, expose a global `ObjectMapper`
2. Expose properties for `List<PayloadConverter>` and `ObjectMapper` that would allow a user to drill down into the current mapper to modify it (this still feels a little hacky, since I would rather treat the current mapper as immutable)
3. Expose something like a `UnaryOperator<ObjectMapper>` that allows a user to customize the mapper alongside Temporal's existing default configuration
4. Expose an environment variable that will trigger Temporal to call `mapper.registerKotlinModule()`
5. Expose an environment variable that will trigger Temporal to call `mapper.findAndRegisterModules()`

Related:
1. https://community.temporal.io/t/hi-deserialization-problem/474/4
6. https://github.com/temporalio/sdk-java/issues/139

Version: `1.16.0`

**Comment by Spikhalskiy** [comment]
You don't need any of this. Create a new `DataConverter` using `DefaultDataConverter#newDefaultInstance()`. Create new `JacksonJsonPayloadConverter` with a `ObjectMapper` configured the way you need. Register your custom `JacksonJsonPayloadConverter` on the `DataConverter` using `DefaultDataConverter#withPayloadConverterOverrides`.
Register your custom `DataConverter` wherever you need.

A similar thing is done in this sample: https://github.com/temporalio/samples-java/blob/708324ffd1599df4d593b411e9516424be096033/src/main/java/io/temporal/samples/payloadconverter/crypto/Starter.java#L49

**Comment by Bennett-Lynch** [comment]
Ah, I missed the `withPayloadConverterOverrides` method. That simplifies things a little bit, thanks. But it seems like I still need to replicate the following code:

https://github.com/temporalio/sdk-java/blob/d2edb5489d9d8e1185e9fcca70208dafc540c82f/temporal-sdk/src/main/java/io/temporal/common/converter/JacksonJsonPayloadConverter.java#L43-L51

**Comment by Bennett-Lynch** [comment]
For anyone else who stumbles upon this, I ended up with a solution like this:

```
val mapper = ObjectMapper().apply {
    configure(DeserializationFeature.ADJUST_DATES_TO_CONTEXT_TIME_ZONE, false)
    configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false)
    findAndRegisterModules()
    setVisibility(PropertyAccessor.FIELD, Visibility.ANY)
}
val dataConverter = DefaultDataConverter.newDefaultInstance()
    .withPayloadConverterOverrides(JacksonJsonPayloadConverter(mapper))
GlobalDataConverter.register(dataConverter)
```

**Comment by Spikhalskiy** [comment]
@Bennett-Lynch You may also want to check out this class from our kotlin module: https://github.com/temporalio/sdk-java/blob/master/temporal-kotlin/src/main/kotlin/io/temporal/common/converter/KotlinObjectMapperFactory.kt

**Comment by Bennett-Lynch** [comment]
> @Bennett-Lynch You may also want to check out this class from our kotlin module: https://github.com/temporalio/sdk-java/blob/master/temporal-kotlin/src/main/kotlin/io/temporal/common/converter/KotlinObjectMapperFactory.kt

Oh, awesome. Is there anyway the default configuration could pick this one up if using SPI or if it's on the class path?

**Comment by Spikhalskiy** [comment]
No, we are not gonna play with SPI as a part of the core. The consequences may be too severe if somebody will have a magically picked up converter that they don’t expect to have. The benefits are not worth the risks.
Also, we fully expect every project to customize their own Jackson settings and these classes are just a start. We are not saying that this configuration makes sense to every project, so we will not automatically load or pick it up.

I will take a look at the discrepancy, but I’m not sure it can be fixed already because of the compatibility concerns.

**Comment by Spikhalskiy** [comment]
https://github.com/temporalio/sdk-java/pull/1388

**Comment by Bennett-Lynch** [comment]
Offering automatic configuration via class-path module detection is a very convenient utility. Without it, I'll now be littering any project using Temporal and Kotlin with manual overrides in both prod/test configuration (which are somewhat cumbersome to insert, due to their global nature). In my case, I'm perfectly happy with the default serialization configuration otherwise. If including such detection in `temporal-kotlin` is too risky, I personally would love to have a separate and dedicated module option, like `temporal-kotlin-jackson`. Just my 2 cents, but I respect your opinion as the maintainer.
