### ISSUE TITLE
[Spring Boot] Support user defined *Customizers for all *Options classes

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1394]
**Describe the solution you'd like**
Spring boot supports externalized configuration, but for full flexibility, JavaSDK Spring Boot should allow users to intercept the creation of all *Options instances to support modification

**Describe alternatives you've considered**
Expose all properties through Spring externalized config. This will work for most cases, but it's not trivial when property values are complicated objects.

**Comment by s-aliasgar** [comment]
We are using 
temporal-sdk: 1.17.0
temporal-spring-boot-starter-alpha: 1.17.0

Is there a way to supply WorkerFactoryOptions and WorkerOptions using configuration properties, since worker creation is abstracted and done internally by springboot
