### ISSUE TITLE
Simplify async activity implementation

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#14]
To not tie up threads users requested support for activity implementations that return CompletableFuture. As we don't want to have Future in the activity API the strawman proposal is to add adapter methods that can be called from activity (similar to Async class from workflow package)

```
class ActivityAsync {
  public static <A1, R> R function(Functions.Func1<A1, CompletableFuture<R>> function, A1 arg1) { ... }
  // similar methods for procedures and argument counts
}
```
Then an activity implementation could look like:

```
String myActivity(String foo) {
   return ActivityAsync.function(myActivityReturningFuture, foo);
}

CompletableFuture<String> myActivityReturningFuture(String foo) {
   ...
}
```

where only `myActivity` method is part of the interface. Then a dynamic proxy adapter can be written to convert from a class that has methods that return ComletableFutures to the activity interface that returns values:

```
interface MyActivities {
   String foo();
   void bar();
}

@ActivitiesImplementation(implements=MyActivities.class)
class MyActivitiesImpl {
   CompletableFuture<String> foo();
   ComletableFuture<Void> bar();
}

```
Then the Worker would just accept `MyActivitiesImpl` instance and internally create the dynamic proxy.

**Comment by vitarb** [comment]
Resolved in https://github.com/temporalio/sdk-java/pull/291
We now provide ability to get a completion client easily thus simplifying user experience.
