### ISSUE TITLE
Allow setting WorkflowOptions via WorkflowImplementationOptions

### ISSUE THREAD

**Issue by roded** [temporalio/sdk-java#1464]
**Is your feature request related to a problem? Please describe.**
Using `WorkflowImplementationOptions`, we can configure default values for `ActivityOptions`. This allows settings these values from by configuration and not injecting or passing configuration objects into the workflow implementations. We'd like to be able to accomplish the same for `WorkflowOptions`. I.e., set the `WorkflowOptions` per workflow in a general location and not only where the workflow stub is created and executed.

**Describe the solution you'd like**
Something like allowing `WorkerOptions` to be set with default `WorkflowOptions` per workflow (if technically possible of course).

**Describe alternatives you've considered**
Injecting configuration options to any code which creates a workflow stub.

**Additional context**
N/A

**Comment by Spikhalskiy** [comment]
It's not possible with the current design, WorkflowOptions have to be defined and set during the workflow start BEFORE the workflow gets dispatched to the worker. So, Workflow Worker can't decide WorkflowOptions. In the same way, ActivityWorker can't define ActivityOptions.

The problem and intention are clear though and we work on a new component that will solve this problem as a part of it's broader functionality.
