### ISSUE TITLE
Spring Boot Starter dependency problem when using Maven

### ISSUE THREAD

**Issue by jrogers** [temporalio/sdk-java#1479]
## Expected Behavior

Including the `temporal-spring-boot-starter-alpha` dependency in a spring boot project fails with a maven validation error.

## Actual Behavior

Get the following error. It looks to be caused by the missing version on the `org.springframework.boot:spring-boot-starter` dependency in the output POM file.

```
[WARNING] The POM for io.temporal:temporal-spring-boot-starter-alpha:jar:1.16.0 is invalid, transitive dependencies (if any) will not be available: 1 problem was encountered while building the effective model for io.temporal:temporal-spring-boot-starter-alpha:1.16.0
[ERROR] 'dependencies.dependency.version' for org.springframework.boot:spring-boot-starter:jar is missing. @ 
```

## Steps to Reproduce the Problem

  1. Include spring boot starter dependency in project:
  ```
          <dependency>
            <groupId>io.temporal</groupId>
            <artifactId>temporal-spring-boot-starter-alpha</artifactId>
            <version>${temporal.version}</version>
        </dependency>
  ```

## Specifications

  - Version: 1.16.0
  - Platform: Mac/Linux

**Comment by Spikhalskiy** [comment]
This is quite strange.

https://repo1.maven.org/maven2/io/temporal/temporal-spring-boot-autoconfigure-alpha/1.16.0/temporal-spring-boot-autoconfigure-alpha-1.16.0.pom
contains
```
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>2.7.3</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```
which should be picked up by temporal-spring-boot-starter-alpha transitively and be enough. Probably some problem in Gradle->Maven exporter plugin.
I will try to add the BOM explicitly to temporal-spring-boot-starter-alpha.

Meanwhile, you can try to add
```
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>2.7.3</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

explicitly in your project to try mitigate the issue.
