### ISSUE TITLE
Spring Boot - add config options for WorkerFactory and Workers

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1488]
Currently it's not possible to define worker factory and worker options via properties/yaml config.

Seems only way is to autowire WorkerFactory and create own workers that then can be configured as needed.

Please add this feature if possible. Thanks.

**Comment by dominicmevin** [comment]
+1

The doc for the spring-boot autoconfigure module says the below
>  '# start-workers: false # disable starting WorkersFactory if you want to make any custom changes before the start'

But this flag just defers the `factory.start()` call as can be seen [here](https://github.com/temporalio/sdk-java/blob/a927dd45ac2e6e0cd98deedc2f3952df58f33ff2/temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/RootNamespaceAutoConfiguration.java#L145), but can't override or make custom changes to the workers already created by the module [here](https://github.com/temporalio/sdk-java/blob/a927dd45ac2e6e0cd98deedc2f3952df58f33ff2/temporal-spring-boot-autoconfigure-alpha/src/main/java/io/temporal/spring/boot/autoconfigure/RootNamespaceAutoConfiguration.java#L135), say in terms of passing in `WorkerOptions` for tuning them.

Defining  worker options via properties/yaml config allows to mitigate the above constraint.
