### ISSUE TITLE
IllegalStateException: Signal received after workflow is closed

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1505]
Forum posts:
https://community.temporal.io/t/unexpected-signal-received-after-workflow-error/6405
https://community.temporal.io/t/signal-received-after-workflow-is-closed/6379

Working on a proper sdk test but just wanted to report and will update when test is done. 
Here is the code the i used to reproduce: https://gist.github.com/tsurdilo/14f538881c511ab0c1c2162fc7286eb0
( you have to start it and let it run for a while sometimes, you might see multiple ContinuedAsNew executions before error happens as signal has to hit the right time)

* Have a workflow that starts a long running activity (in loop) inside cancellation scope. Loop is for 10 activity invocations, then it calls continueasnew
* Workflow has a signal method which cancels the scope of the currently running activity inside that loop in wf
* Client keeps sending signals for cancellation to this workflow

Seems that when a signal comes in at same time as workflow calls continueasnew, worker raises UnhandledCommand to extend the workflow task and handle that signal, on next workflow task the signal is processed, tries to cancel CancellationScope and the wf task fails again with:

<img width="1686" alt="Screen Shot 2022-11-05 at 9 39 04 PM" src="https://user-images.githubusercontent.com/119422/200150501-1979159d-52c8-4f66-bb1c-c99a54b69eee.png">

at this point the workflow task keeps failing and replaying.

**Comment by Quinn-With-Two-Ns** [comment]
Testing the reproduction on the latest SDK https://gist.github.com/tsurdilo/14f538881c511ab0c1c2162fc7286eb0 it does not cause any `IllegalStateException` on the latest SDK
