### ISSUE TITLE
How to gracefully shut down a temporal worker

### ISSUE THREAD

**Issue by sherifr212** [temporalio/sdk-java#1522]
Hello,

I am using Java SDK, and I was wondering how to gracefully shut down a worker that executes my workflows without any data loss or corruption?
Or even re-executing steps/tasks/activity code?

**Comment by Spikhalskiy** [comment]
Please use Temporal community slack to ask questions: https://temporal.io/community

JavaSDK has `WorkerFactory#shutdown` method that allows to gracefully shutdown workers.
