### ISSUE TITLE
TLS server for java sdk connection option.

### ISSUE THREAD

**Issue by XingLiu0923** [temporalio/sdk-java#1541]
**Is your feature request related to a problem? Please describe.**
Before I connect to my Temporal cluster, I need to connect to the TLS server to get certificate then I could connect to the Temporal cluster. In go language, I could do like below:
```
var connOptions client.ConnectionOptions
	if cfg.Temporal.TLSServer != "" {
		connOptions = client.ConnectionOptions{
			TLS: &tls.Config{
				ServerName: cfg.Temporal.TLSServer,
			},
		}
	}

c, err := client.NewClient(client.Options{
	HostPort:          cfg.Temporal.HostPort,
	Namespace:         cfg.Temporal.Namespace,
	ConnectionOptions: connOptions,
})
```
But in java, i did not find way to do this.

**Describe the solution you'd like**
Got a way to set TLS server in java.

**Describe alternatives you've considered**
I did not find alternatives ...

**Comment by Spikhalskiy** [comment]
Use `ServiceStubsOptions#setChannelInitializer` to intercept the creation of grpc's `ManagedChannelBuilder`. On grpc `ManagedChannelBuilder` you can set a custom tls server name in `overrideAuthority#overrideAuthority`.

Please use Temporal forum or Slack community to ask questions: 
https://community.temporal.io
https://t.mp/slack

**Comment by XingLiu0923** [comment]
> Use `ServiceStubsOptions#setChannelInitializer` to intercept the creation of grpc's `ManagedChannelBuilder`. On grpc `ManagedChannelBuilder` you can set a custom tls server name in `ManagedChannelBuilder#overrideAuthority`.
> 
> Please use Temporal forum or Slack community to ask questions: https://community.temporal.io https://t.mp/slack

Got it. Thanks for the reply! Sorry for asking in wrong place. now i know where to ask, thanks!
