### ISSUE TITLE
Dynamic & interpolated taskQueues 

### ISSUE THREAD

**Issue by karneyli** [temporalio/sdk-java#1550]
The spring boot auto discovery doesn't allow taskQueues to be set programmatically or through property interpolation/resolution.  

In the java-samples, the [FileProcessingWorker](https://github.com/temporalio/samples-java/blob/main/src/main/java/io/temporal/samples/fileprocessing/FileProcessingWorker.java#L57) registers the `StoreActivitiesImpl` to two different task queues, one shared and one host name specific.  There's no way to do this currently if we go the spring boot autoconfigured route.  The `WorkersTemplate` doesn't have a way to delegate `taskQueues` to a resolver function.  Ideally, it would work similar to how JUnit's @ParameterizedTest + @MethodSource works.

The `WorkersTemplate` also doesn't do property value interpolation, so all the taskQueues end up having just being a list of hardcoded strings in the @ActivityImpl annotation, it would be nice if some of the values could come from application properties config.

**Comment by Spikhalskiy** [comment]
> The spring boot auto discovery doesn't allow taskQueues to be set programmatically or through property interpolation/resolution.

Please take a look at the Readme:
https://github.com/temporalio/sdk-java/tree/master/temporal-spring-boot-autoconfigure-alpha#explicit-configuration

**Comment by karneyli** [comment]
The explicit configuration is an option and would address at least the
taskQueues through properties but not the programmatic / dynamic use case.
Auto-configuration by package is far less toil than listing out all classes
and beans.  Mixing the two styles according to the documentation is not
well-defined in terms of behaviour.

**Comment by Spikhalskiy** [comment]
For programmatic/dynamic usecase Spring boot configuration approach is not that great anyway.
Our Spring boot doesn't and will not have a goal of unlimited extensibility, it will be opinionated to keep things easy for most typical usages.
Users that need unlimited flexible configuring should just configure the WorkerFactory from their code not using Spring Boot module.

**Comment by Spikhalskiy** [comment]
Closed by #1623
