### ISSUE TITLE
Return not-found with `NamespaceNotFoundFailure` when namespace not found (and other errordetails)

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-java#1557]
**Is your feature request related to a problem? Please describe.**

When calling `DescribeNamespace` for unknown namespace, no error raised

**Describe the solution you'd like**

Return not found error with `temporal.api.errordetails.v1.NamespaceNotFoundFailure` in the gRPC status details. Also support any missing error details from https://github.com/temporalio/api/blob/master/temporal/api/errordetails/v1/message.proto on other calls.

**Comment by Spikhalskiy** [comment]
Right now Test Server supports all namespaces as registered for user convenience. It's a design choice.

**Comment by cretz** [comment]
Ok, I will close this as intentional deviation from regular server and for my test that confirms behavior on unregistered namespace, I'll just skip the test server for now
