### ISSUE TITLE
Test server seems to not enable time skipping in this specific scenario

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-java#1565]
## Expected Behavior

W2 7 day timer should be unblocked immediately.

## Actual Behavior

Timer is not unblocked.

## Steps to Reproduce the Problem

(I have not run this myself and verified, this is pseudo code I got from a user on [slack](https://temporalio.slack.com/archives/C01DKSMU94L/p1670625163595479))

```ts
async function W1() {
    await A1();
    ...
}

async function A1() {
  const ids = runDBQuery();

  const { workflowClient } = getContext();

  await Promise.all(
    ids.map((id) =>
      workflowClient.signalWithStart(W2, {
        taskQueue: "default",
        workflowId: `W2-${id}`,
        args: [
          {
            ...
          },
        ],
        signal: S1,
        signalArgs: [{ ... }],
      })
    ),
  );
}

async function W2() {
    await sleep("7 days");
    await A2();
    ...
}

async function A2() {
    // produce side effect
}

describe("test T1", () => {
    it("alls A2", async () => {
        const testActivities = {
          ...activities,
          A2: jest.fn(),
        };


        const testEnv = await TestWorkflowEnvironment.createTimeSkipping();
        const worker = await Worker.create({
          connection: testEnv.nativeConnection,
          workflowsPath: require.resolve("./allWorkflows"),
          interceptors: appendDefaultInterceptors(
            {
              activityInbound: [
                (ctx) =>
                  new CustomActivityInboundInterceptor(ctx, {
                    workflowClient: testEnv.client.workflow,
                  }),
              ],
            },
            console
          ),
          activities: testActivities,
          taskQueue: "default",
        });

        await worker.runUntil(() => 
          testEnv.client.workflow.execute(
            W1,
            {
              workflowId: randomUUID(),
              taskQueue: "default",
              args: [
                {
                  ...
                },
              ],
            }
          )
        )

        const handle = testEnv.client.workflow.getHandle(`W2-id1`);
        await handle.result();

        expect(testActivities.A2).toHaveBeenCalled();
    })
})
```

**Comment by maxgurewitz** [comment]
Thank you!

**Comment by Spikhalskiy** [comment]
Workflow Time skipping is getting disabled for the period of activity execution. You don't want the Server time to become infinity while you execute your activity, you want it to reflect the actual time of the activity execution.

**Comment by Spikhalskiy** [comment]
What does A1 wait for in this code sample? Does it wait for workflow start or completion?

**Comment by maxgurewitz** [comment]
> Does it wait for workflow start or completion?

A1 just waits until the `workflowClient.signalWithStart` calls complete, which as I understand it will just wait until A2 starts, not completes.

**Comment by maxgurewitz** [comment]
If this is not a bug, is there some recommended in the above pseudocode?

**Comment by maxgurewitz** [comment]
> The WorkflowClient that is used in the activity A2 may be reconfigured to use the time-skipping workflow client, the testEnv.client one to address this change. This doesn't require a Test Server change.

If I'm understanding you, I believe I'm doing that by injecting the time-skipping workflow client with an interceptor.

**Comment by Spikhalskiy** [comment]
@maxgurewitz Thanks for the clarification, it makes more sense if they wait only for a start. I will try to repro it and get back to you, I don't expect it to be a Test Server bug, but it may be a TS SDK bug. 
How many workflows does A1 start in your test? One or several?

**Comment by maxgurewitz** [comment]
> How many workflows does A1 start in your test? One or several?

It can start several, but I can repro this issue where it only starts 1 (`ids` has 1 item).

**Comment by bergundy** [comment]
Looks like the worker in this example is shut down before the second workflow gets a chance to complete.
