### ISSUE TITLE
ExternalWorkflowStub query

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1584]
Feature request is to please add ability to query via ExternalWorkflowStub. Currently signal is only possible.

**Comment by Spikhalskiy** [comment]
This is not an SDK issue. ExternalWorkflowStub has an underlying implementation in state machines and produces commands. There is no command and no underlying workflow history baked implementation for query currently.
So, this needs a new command and Server support first.
Workaround: use an activity to query an external workflow.

**Comment by rocketraman** [comment]
Do we have a tracking issue for the new command and server support for this? I also can't do `@Update` from a parent workflow, and it is quite an annoyance to have to delegate the call to an activity.
