### ISSUE TITLE
Allow WorkflowImplementationOptions to be passed in TestWorkflowExtension->setWorkflowTypes

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1626]
TestWorkflowRule:

       public Builder setWorkflowTypes(
           WorkflowImplementationOptions implementationOptions, Class<?>... workflowTypes) { ... }

TestWorkflowExtention:

       public Builder setWorkflowTypes(Class<?>... workflowTypes) { ... }

Allow WorkflowImplementationOptions to also be passed in setWorkflowTypes in TestWorkflowExtention.

**Comment by picpromusic** [comment]
@tsurdilo is there a workaround when working with TestWorkflowExtension?
