### ISSUE TITLE
Schedule API example with Spring boot

### ISSUE THREAD

**Issue by smaldored** [temporalio/sdk-java#1666]
Hey there. I was looking to start using the new schedule API as talked about here https://docs.temporal.io/workflows#schedule
and was wondering if there are any examples using spring-boot? I saw a commit from last July that implemented a high-level schedule API, is that what I'm to use?

If there are any starting points or examples I could look at for the new Temporal schedule API with Spring boot,  that would be much appreciated!

**Comment by mjameswh** [comment]
The Java SDK does not yet provide a high level Schedule API. Maybe you saw [this ticket](https://github.com/temporalio/sdk-java/issues/1333), dated from last July, which tracks this as a feature to be implemented. This is on our road map.

**Comment by smaldored** [comment]
@mjameswh Yes that is exactly what I saw. Thank you for the insight. Do you have any estimate as to when this may be available?

If not, are there any examples of the older way of doing it via temporal cron job?

Thanks for the quick response!

**Comment by mjameswh** [comment]
> Do you have any estimate as to when this may be available?

We don't have an ETA for this, but it is on our short term list.

> If not, are there any examples of the older way of doing it via temporal cron job?

We have an example of using cron workflows [here](https://github.com/temporalio/samples-java/blob/main/src/main/java/io/temporal/samples/hello/HelloCron.java).

Alternatively, you may use the new Schedule feature right now, using the raw gRPC API. For the kind of things that can be accomplished using cron workflows, the raw gRPC API should not be difficult to master. We don't have a Schedule-specific example, but you may have a look at this [example](https://github.com/temporalio/samples-java/blob/27469ab52a4aa011a4927343aec4db34448c0008/src/main/java/io/temporal/samples/terminateworkflow/Starter.java#L107-L108) showing how to use the raw gRPC API. The API would want to call is `WorkflowService/CreateSchedule`.

**Comment by Quinn-With-Two-Ns** [comment]
A schedule sample is available in our [samples repo ](https://github.com/temporalio/samples-java/blob/main/core/src/main/java/io/temporal/samples/hello/HelloSchedules.java)

Springboot does not effect schedules so a spring  boot specific example wouldn't provide much value
