### ISSUE TITLE
Inheritance with @WorkflowMethod annotation

### ISSUE THREAD

**Issue by Bennett-Lynch** [temporalio/sdk-java#1669]
I'd like to create base interfaces and abstract classes for common workflow patterns. While possible, Temporal does not discover the `@WorkflowMethod` annotation from parent classes:

> You can create interface inheritance hierarchies to reuse components across other Workflow interfaces. The interface inheritance approach does not apply to `@WorkflowMethod` annotations. [[source]](https://legacy-documentation-sdks.temporal.io/java/how-to-develop-a-workflow-definition-in-java)

Is there any reason for this limitation? If the risk is multi-inheritance of `@WorkflowMethod` methods, could that simply be a runtime violation or unspecified behavior?

The workaround is to redeclare and annotate the method, which results in unnecessary code and may be more error prone.

**Comment by cretz** [comment]
I'll let @Spikhalskiy answer for Java, but I can say we have the same intentional attribute/decorator inheritance limitation in .NET/Python very specifically because we _want_ you to have to annotate the most overridden form. These annotations mark methods as special and therefore hiding whether they are special up the inheritance chain is error prone.

> which results in unnecessary code and may be more error prone.

We intentionally accept that it adds more code, but how is it more error prone?

**Comment by Bennett-Lynch** [comment]
It can be more error prone in that someone implementing an abstract workflow class may not know they need to redeclare and annotate methods, and these misses may not be discovered until runtime (often with obscure serialization errors). It's counter-intuitive to how people normally interact with abstract classes.

**Comment by Spikhalskiy** [comment]
@WorkflowMethod annotation pretty much defines a workflow type.
```
public @interface WorkflowMethod {
  /** Name of the workflow type. Default is {short class name} */
  String name() default "";
}
```

We don't want this annotation to be placed on a parent class with multiple children explicitly to point this out.

You can still use inheritance, just override the method, annotate it with a right @WorkflowMethod and delegate it to the parent.

**Comment by cretz** [comment]
> these misses may not be discovered until runtime (often with obscure serialization errors)

In some languages we validate up the inheritance chain at registration time. So if you have an override that doesn't define the Temporal annotation its base signature does, we error at registration time. I could see that extra validation having value.

**Comment by Bennett-Lynch** [comment]
> @WorkflowMethod annotation pretty much defines a specific workflow type and there should be one workflow of the specific type in most apps.

Isn't this true for `@WorkflowInterface` but not necessarily `@WorkflowMethod`?

I'll give a slightly more concrete example for a use case I have in mind:

I'm designing an interface and corresponding abstract class for a workflow that is primarily signal-driven. The abstract class facilitates polling for signals, deduplicating signals, etc. Implementations of the abstract class can then simply instrument the behavior to react to the signal and decide if it's terminal.

In this scenario I want to offer this abstract class as a library, and there may be multiple implementations of it within a single application. So I would not wish to declare `@WorkflowInterface` at the abstract class level, but it does make sense to declare `@WorkflowMethod` at the abstract class level.

Implementations of the abstract class then need to mostly pointlessly redeclare the `startworkflow` method just to add an annotation. In my opinion it makes sense and offers value for Temporal to be able to discover this annotation through inheritance.

**Comment by Spikhalskiy** [comment]
We don't want `@WorkflowMethod`'s to be flying around and leaking without any attachment to the `@WorkflowInterface`, this is the idea and a design.
Both `@WorkflowInterface` and `@WorkflowMethod` work together to define a workflow type.
What a `@WorkflowMethod` annotation with a specified `name` in the parent class means if it's not a WorkflowInterface implementation at all?

> So I would not wish to declare @WorkflowInterface at the parent interface level, but it does make sense to declare @WorkflowMethod at the parent interface level.

You parent class is not implementing a @WorkflowInterface, it shouldn't have WorkflowMethods. It's not workflow methods. It's just methods.
Children that implement @WorkflowInterface may MAKE them @WorkflowMethod by overriding them.

**Comment by Bennett-Lynch** [comment]
Thanks @Spikhalskiy. I can understand that reasoning even if I'm not 100% in agreement with the design.

However, if you argue that these workflow-related annotations are meaningless when not associated with a workflow interface, wouldn't the same be true for something like `@Signal`? But the documentation [here](https://legacy-documentation-sdks.temporal.io/java/workflows) suggests creating reusable interface components as follows:

```
public interface Retryable {
    @SignalMethod
    void retryNow();
}
```

```
@WorkflowInterface
public interface MediaProcessingWorkflow extends Retryable {

    @WorkflowMethod
    String processBlob(Arguments args);
}
```

`Retryable` is not a workflow interface so by the same logic it should not be allowed to contain any workflow-related annotations.

**Comment by cretz** [comment]
"Mixins" (not a term you hear in Java much but applicable in other langs where we have this same rule) and multi-inherited interfaces can have value for signals and queries which can have > 1 arity and be composable with unrelated sets of each other, but workflow methods are singular and not composable in that way.

**Comment by Bennett-Lynch** [comment]
IMHO, regardless of arity, inheritance is just a way to help organize and abstract code and it would be nice if the Temporal SDK allowed developers to make their own judgment call on how it is structured. I'll make one final plea to consider the same and otherwise I appreciate the opinions and respect the design decision. :)
