### ISSUE TITLE
Closing metric subscopes surprisingly closes the parent scope as well

### ISSUE THREAD

**Issue by tylercunnion** [temporalio/sdk-java#1684]
## Expected Behavior
Creating a subscope using code such as:
```java
Scope taggedScope = Workflow.getMetricsScope().tagged(
    Map.of("tag", "value")
);
```
produces a new instance of ReplayAwareScope including the tag. Since this is an instance of `Scope` and thus `AutoCloseable`, the IDE is going to suggest it be wrapped in a `try-by-resources` (or at least raise some kind of warning that the object should be closed). 

My **expected behavior** is that invoking `close()` on this object should only close this object itself, ie the subscope would no longer be available for use. 

## Actual Behavior

Closing the subscope invokes the `close()` method of `ReplayAwareScope`, which in turn closes its contained instance of `Scope`; the effect is that the metrics scope for the _entire worker_ is silently closed, and no more metrics will be reported.

## Steps to Reproduce the Problem

  1. Create a subscope using `.tagged()` or `.subscope()`. 
  1. Call the `close()` method, either explicitly or implicitly using `try-with-resources`. 

## Specifications

  - Version: 1.18.2
  - Platform: linux

**Comment by tylercunnion** [comment]
This may just need to be a documentation enhancement honestly, but it's bitten me twice now (after I completely forgot about the problem between the first and second) so I figured it was worth raising.

**Comment by Spikhalskiy** [comment]
Scope abstraction, contracts and implementation is not Temporal Java SDK abstraction, it’s uber-tally, our transitive dependency. 
If and when we create our own Scope abstraction, it will be one of the things that we will do differently.
So, while I agree with you on your points in terms of user friendliness, we don’t control tally’s abstractions, we use them.

**Comment by tylercunnion** [comment]
Got it - I was thinking the issue was specifically ReplayAwareScope closing its inner Scope but I see that tally's subscopes close their reporter as well so it's really moot. Thanks for the quick response!
