### ISSUE TITLE
WorkerFactoryOptions getDefaultInstance() does not return the default instance

### ISSUE THREAD

**Issue by cherry-lim** [temporalio/sdk-java#1703]
## Expected Behavior
WorkerFactoryOptions getDefaultInstance() should return the default instance where the max cache size, max thread count etc. are set to the default values

## Actual Behavior
WorkerFactoryOptions getDefaultInstance() does not return the instance with default values

## Steps to Reproduce the Problem

  1. call WorkerFactoryOptions.getDefaultInstance() and look at the fields

## Specifications

  - Version: 1.17.0
  - Platform:

**Comment by Spikhalskiy** [comment]
The instance returned by WorkerFactoryOptions#getDefaultInstance will lead to the default configuration if it's used to create WorkerFactory.
We don't publish fields that were not overriden to support merging of properties.

**Comment by Spikhalskiy** [comment]
If you want to read the default values for whatever purposes, you may use ```WorkerFactoryOptions.newBuilder().validateAndBuildWithDefaults()```
