### ISSUE TITLE
Synchronous workflow update

### ISSUE THREAD

**Issue by fourth-engineer** [temporalio/sdk-java#1708]
**Is your feature request related to a problem? Please describe.**
Yes

Provide the implementation on the Java SDK for following feature
https://github.com/temporalio/temporal/pull/3822

**Describe the solution you'd like**
https://github.com/temporalio/temporal/pull/3822

**Describe alternatives you've considered**
NA

**Additional context**
https://github.com/temporalio/temporal/pull/3822

**Comment by bergundy** [comment]
We are currently working on this.

**Comment by jeenadeepak** [comment]
@bergundy : Any update here?

**Comment by Quinn-With-Two-Ns** [comment]
@jeenadeepak Still in progress, this issue will be closed when it is implemented.

**Comment by Quinn-With-Two-Ns** [comment]
Closing as implemented here https://github.com/temporalio/sdk-java/issues/1745 will be release in v1.20
