### ISSUE TITLE
Signal with a local activity in the last Workflow Task hangs the workflow execution

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#1722]
"last workflow task of the workflow" in this ticket means the WFT that will complete workflow method execution and will lead to `CompleteWorkflowExecution` command. 

## Expected Behavior

If the workflow receives a signal in the last workflow task, this signal should be successfully processed first and the workflow should complete after that.

## Actual Behavior

If workflow receives a signal with the last workflow task and this signal starts a local activity and the workflow method is not explicitly waiting for the signal completion, it leads to 

```
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: invalid command sequence: [CompleteWorkflowExecution, RecordMarker], command CompleteWorkflowExecution must be the last command.
```

See https://github.com/Spikhalskiy/java-sdk/commit/c0a397ec4e5e0101b70f417ff4d244df7c291c26 for a test reproducing the problem.

## Proposed solutions

One of:

1. Completion of the workflow method shouldn't lead to an immediate `CompleteWorkflowExecution` command. Instead, `CompleteWorkflowExecution` should be issued at the end of that workflow task.
2. Completion of the workflow method shouldn't lead to an immediate `CompleteWorkflowExecution` command. Instead, `CompleteWorkflowExecution` should be issued at the end of all workflow threads (including Async and Signal)
3. If the first two are hard to implement and maintain backward compatibility, CompleteWorkflowExecution` should be the last command written. All commands after it should be discarded. This is the least graceful way of handling this situation.

**Comment by longquanzheng** [comment]
Hey @Spikhalskiy , probably just ciruous, is that only an issue with local activity? What about other commands like activity scheduled or childWF or upsert search attributes?

**Comment by Spikhalskiy** [comment]
It's true for any command happening in a signal after a yield if the workflow method doesn't wait for the signal method completion.
