### ISSUE TITLE
Add attempt to MDC context of the activity worker handler

### ISSUE THREAD

**Issue by rp-julienguery** [temporalio/sdk-java#1731]
**Is your feature request related to a problem? Please describe.**
Having the attempt added to the MDC context of the activity worker handler would allow me to differentiate between two activity attempts...

**Describe the solution you'd like**
Add the following lines to the `ActivityWorker#handle` and `LocalActivityWorker#handle` methods.

```java
MDC.put(LoggerTag.ACTIVITY_ATTEMPT, pollResponse.getAttempt());
...
MDC.remove(LoggerTag.ACTIVITY_ATTEMPT);
```

**Comment by Quinn-With-Two-Ns** [comment]
Closed in https://github.com/temporalio/sdk-java/commit/f2e113a49ba5d3d5b7a178bcaf14e6fb1e0df878
