### ISSUE TITLE
Workflow Task Exception eats up the exception sent by code

### ISSUE THREAD

**Issue by hrishirc** [temporalio/sdk-java#1736]
## Expected Behavior
After getVersion call, the same workflow task eats up a business logic exception

## Actual Behavior
The exception should not be eaten up. Instead the business logic exception should come in the Temporal UI

## Steps to Reproduce the Problem

  1. Version a piece of code
  1. Send an exception immediately after that line

## Specifications

  - Version: 1.16
  - Platform: Java SDK

https://gist.github.com/hrishirc/68c6fcc23b7c943f858d91fe451f689a

**Comment by hrishirc** [comment]
any update on this?

**Comment by hrishirc** [comment]
any update on this?

**Comment by Spikhalskiy** [comment]
This issue needs a reproduction or more information about the specific code structure causing it.
I wrote [a test verifying the behavior of a simple getVersion + exception right after](https://github.com/temporalio/sdk-java/blob/d1ad622e243501d7c435deda4fe34e60c1be41c7/temporal-sdk/src/test/java/io/temporal/workflow/versionTests/GetVersionFollowedByRandomExceptionTest.java#L54) and verified that it passes against the current master and 1.16.0.

**Comment by Quinn-With-Two-Ns** [comment]
Closing for now as not enough information is here, if more is provided we can reopen
