### ISSUE TITLE
Workflow Update: Java

### ISSUE THREAD

**Issue by Quinn-With-Two-Ns** [temporalio/sdk-java#1741]
# Description

Add support for workflow update to Java SDK.

# Core Objectives

This feature will allow users to issue update requests to a workflow, have that workflow process the update (accessing and mutating internal workflow state as necessary) and return a response to the caller. This functionality will be available from external workflows as well as from code external to Temporal altogether.

# Issues
- [x] #1745
- [x] #1742
- [x] #1743
- [x] #1744
- [x] #1748
- [ ] #1769
- [ ] #1781

# Related user requests / reports
- [x] #1708

# External Issues

- [x] https://github.com/temporalio/features/issues/266

**Comment by josh-berry** [comment]
Consolidating the remainder of the work under https://github.com/temporalio/features/issues/296
