### ISSUE TITLE
Making activity prefix and name generation pluggable

### ISSUE THREAD

**Issue by osi** [temporalio/sdk-java#1751]
**Is your feature request related to a problem? Please describe.**

I am repeating the same logic in my `@ActivityInterface(namePrefix = "...")` annotations. I would like to have this expressed in code, rather than a manually-applied pattern.

In the code, I saw a [TODO for this](https://github.com/temporalio/sdk-java/blob/c1cff1c5d9ef6e3ef23301fd5ff5260545d83125/temporal-sdk/src/main/java/io/temporal/common/metadata/POJOActivityMethodMetadata.java#L47).

I am interested in helping develop a PR for this and would like to understand any existing thoughts.

**Comment by Quinn-With-Two-Ns** [comment]
Hi @osi We already have an issue open for this [here](https://github.com/temporalio/sdk-java/issues/396#issuecomment-1558567608) so closing this issue in favor of that one. We'd welcome a contribution in this area so feel  free to propose a design if you'd like.
