### ISSUE TITLE
Register Same Interface Multiple Times

### ISSUE THREAD

**Issue by MrThreepwood** [temporalio/sdk-java#1763]
Firstly, this may just be a question, it's likely that I'm missing/misunderstanding something.

**Is your feature request related to a problem? Please describe.**
We would like to use temporal as a testing framework. Each workflow needs to be wrapped in some logic to best handle creating traces (we're using Data Dog for trace information and error reporting) and reporting errors. We don't mind (and even prefer) all the test entry points having the same signature. So, from a language standpoint this is very simple, we have a single abstract class that handles the initial signal and has all the trace creation logic. It then calls a set function on the actual implementation to handle the workflow. The problem I'm running into is that I'm not sure how to register this with the java sdk. It's expecting an interface declared in the top level class, and has no way to register the same interface/abstract class multiple times with different names (other SDK look like they allow registering a workflow name with workflow options)

**Describe the solution you'd like**
Preferably I'd like something like the Go api that allows you to register a function (or class/factory) and override its name in the registration to allow registering multiple workflows with the same worker. Ideally I'd like to not require an interface either.

**Describe alternatives you've considered**
We could simply create a new worker for each test, but that's likely to end up with hundreds of workers all long-polling temporal for work, which doesn't seem ideal.

**Comment by Quinn-With-Two-Ns** [comment]
A workflow interface represents a workflow type, a worker can only have one implementation for each workflow type. This situation sounds like they each are different workflow type's so they should each have their own interface. Alternatively you could use a [dynamic workflow](https://github.com/temporalio/samples-java/blob/69db54524cccd94634cd81a551c724312e74c471/core/src/main/java/io/temporal/samples/hello/HelloDynamic.java#L38) and switch in the workflow.
