### ISSUE TITLE
Detailed message for exceptions

### ISSUE THREAD

**Issue by yashwantakashlal** [temporalio/sdk-java#1785]
**Is your feature request related to a problem? Please describe.**
When a workflow is already started and we try to start one more workflow with the same workflowId - we get io.temporal.client.WorkflowExecutionAlreadyStarted exception with message containing workflow details - workflowId='xxxxx', runId='yyy' - basically this - 
io.temporal.client.WorkflowExecutionAlreadyStarted: workflowId='xxxxx', runId='yyyyy'

**Describe the solution you'd like**
A clear and concise message should be thrown along with workflow details which denotes that workflow has already started with this id along with the workflow details.

**Additional context**
Screenshot of temporal slack discussion for context.
<img width="735" alt="Screenshot 2023-06-12 at 10 34 45 PM" src="https://github.com/temporalio/sdk-java/assets/65457583/0102bc44-b587-4eec-b922-8b7164b23c90">

**Comment by yashwantakashlal** [comment]
hi @tsurdilo / @Spikhalskiy , is this being worked upon by someone ? just wanted to understand if this is being taken forward, if not I might give it a try as well.

**Comment by Quinn-With-Two-Ns** [comment]
Unlikely this would be taken forward, the intention is users deduce the message from the exception type and  changing the message would be a backwards incompatible change to `WorkflowExecutionAlreadyStarted`.
