### ISSUE TITLE
Make ProtobufPayloadConverter and ProtobufJsonPayloadConverter not final

### ISSUE THREAD

**Issue by stephenchen-humane** [temporalio/sdk-java#1824]
As part of writing our custom protobuf payload converters, we would like to extend the default ones for `json/protobuf` and `binary/protobuf` directly rather than extending the AbstractProtobufPayloadConverter and copying code from each impl. We cannot because the implementing classes are marked with `final`.

**Comment by cretz** [comment]
I think it may be best if you just make a new payload converter and delegate to the one you want instead of using inheritance. The interfaces are quite small.

**Comment by stephenchen-humane** [comment]
sounds good, it is simple enough to not use inheritance.
