### ISSUE TITLE
Fix WorkerOptions equals method

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1854]
WorkerOptions equals is failing with NullPointer if buildid is not explicitly set. To reproduce:

          WorkerOptions w1 = WorkerOptions.newBuilder().build();
          WorkerOptions w2 = WorkerOptions.newBuilder().build();
          assertTrue(w1.equals(w2));

This is due to added buildid in equals without a null check for it:
https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/worker/WorkerOptions.java#L582

**Comment by tom-stu** [comment]
Thanks Tihomir! I cloned the temporal java sdk repo and made a fix for this locally. I am waiting for legal to give me permission to sign the Contributor License Agreement before I make a pull request (so someone on your side might get around to fixing it first), but I may end up creating a pull request for this if it's still an issue if/when legal department gives me the OK to contribute to your code base  😄
