### ISSUE TITLE
use spring boot sdk, how to run workflow

### ISSUE THREAD

**Issue by starboyate** [temporalio/sdk-java#1867]
when I use temporal-spring-boot-starter-alpha,I hava a question, how to run workflow?

**Comment by Quinn-With-Two-Ns** [comment]
There are a number of ways to start a workflow, we have a guide here https://docs.temporal.io/dev-guide/java/foundations#start-workflow-execution

**Comment by Quinn-With-Two-Ns** [comment]
Closing since this is not an SDK issue, feel free to ask general questions on our [forum](https://community.temporal.io/) or [community slack ](https://app.slack.com/client/TNWA8QCGZ/CNWA8QH09)
