### ISSUE TITLE
Unable to build on Ubuntu Linux for aarch64 (ARM)

### ISSUE THREAD

**Issue by uromahn** [temporalio/sdk-java#1883]
**Is your feature request related to a problem? Please describe.**
I am trying to build the sdk-java from source on my Ubuntu Linux running on aarch64 (ARM) HW architecture. I am unable to do that since the protoc executable being pulled in is for Mac OS X.
See `build.gradle` in `temporal-serviceclient`:
```
    protoc {
        artifact = 'com.google.protobuf:protoc:3.10.1' + (System.getProperty("os.arch") == 'aarch64' ? ':osx-x86_64' : '')
    }

```

**Describe the solution you'd like**
The gradle.build file needs to also consider the OS and pull in the correct protoc executable.
For Linux aarch it should be [protoc-3.10.1-linux-aarch_64.exe](https://repo1.maven.org/maven2/com/google/protobuf/protoc/3.10.1/protoc-3.10.1-linux-aarch_64.exe)

**Describe alternatives you've considered**
Building from source on OSK

**Additional context**
- none -

**Comment by Quinn-With-Two-Ns** [comment]
Yeah makes sense, looks like an oversight.
