### ISSUE TITLE
TemporalTestServer add support to test schedules

### ISSUE THREAD

**Issue by antmendoza** [temporalio/sdk-java#1954]
**Is your feature request related to a problem? Please describe.**
I would like to have the possibility to use the [temporal-test-server](https://github.com/temporalio/sdk-java/tree/master/temporal-test-server) to test [schedules](https://docs.temporal.io/workflows#schedule) 

**Describe the solution you'd like**

**Describe alternatives you've considered**
Run schedule test using a real/local server for now.

**Additional context**

**Comment by cretz** [comment]
The test server isn't really built well to be a multi-workflow server. You'd never be able to properly test multiple schedules or an overlapping schedule because they test server doesn't support concurrent, independent workflow runs (time skipping is server-wide not per workflow).

**Comment by Quinn-With-Two-Ns** [comment]
The time skipping test server is meant to cover testing individual workflow not features like schedules, it would require a complete re do of schedules in Java for little gain vs using a real server.

Going to close since we have no plans to do this.
