### ISSUE TITLE
Missing Retry Policy on Continue-As-New

### ISSUE THREAD

**Issue by MatthewHou** [temporalio/sdk-java#1959]
## Expected Behavior
RetryPolicy should either be propagated or accepted as part of the `ContinueAsNewOptions` for Contine-As-New

## Actual Behavior
RetryPolicy is not set in the new workflow execution when `contineAsNew` is called. 
And we are not able to explicitly set `RetryOptions` when calling `contineAsNew`  since it is not included in the `ContinueAsNewOptions`. 

## Steps to Reproduce the Problem

  1. Start a workflow with a retry policy
  2. Workflow continued as new
  3. The retry policy is not set for the new workflow execution

## Specifications

  - Version: Java SDK 1.22.3
  - Platform: Java SDK

**Comment by MatthewHou** [comment]
Retry Options and other attributes are propagated by default in Go SDK and Python/TS SDK. This should help Java SDK to align the behaviour on continue-as-new. Please see the following issues

- https://github.com/temporalio/sdk-go/issues/695 
- https://github.com/temporalio/sdk-core/issues/372

**Comment by Quinn-With-Two-Ns** [comment]
closed by https://github.com/temporalio/sdk-java/pull/1961
