### ISSUE TITLE
SpringBoot - add "server-name" property to connection options

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#1996]
Feature request to add "server-name" to connection options. This can be useful for users going through PrivateLink or similar.
This would use ManagedChannelBuilder#overrideAuthority to set the server name directly rather than getting it from target.

Note this is currently possible to configure via TemporalOptionsCustomizer, but is useful for convenience.

**Comment by cretz** [comment]
This is a TLS-specific option, can we make sure it is presented the same way as other TLS options?
