### ISSUE TITLE
ensureDefaultFieldsForActivityRetryPolicy in testService don't rewrite nonRetryableErrorTypes

### ISSUE THREAD

**Issue by filipmigdalski** [temporalio/sdk-java#203]
## Actual Behavior
It seems that `io.temporal.internal.testservice.StateMachines.ensureDefaultFieldsForActivityRetryPolicy(RetryPolicy originalPolicy)` don't rewrite nonRetryableErrorTypes. There are no corresponding instructions in the method.

**Comment by filipmigdalski** [comment]
I've made a quickfix (it's one-liner + tests), but i can't push it into a new branch

**Comment by skrul** [comment]
Hey @filipmigdalski I believe this issue is currently blocking me from upgrading to v0.29.1 as my code has a unit test that checks if the `setDoNotRetry` retry policy is respected.

**Comment by Spikhalskiy** [comment]
Closed by #223
