### ISSUE TITLE
Add toString method to WorkflowServiceStubsOptions

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#2047]
improvement request to add toString method to WorkflowServiceStubsOptions that would print out all options available. can be extended to any/all other options type of classes

**Comment by dskarbek** [comment]
Please make sure to add a toString method to the Builder sub-class as well so we can log what options we are building with.

**Comment by Quinn-With-Two-Ns** [comment]
We should also include `equals` and `hashcode` like all other `*Options` in the Java SDK. The `Builder` can be converted to a `WorkflowServiceStubsOptions` to be logged.

**Comment by Quinn-With-Two-Ns** [comment]
We also need to do this for `OperatorServiceStubsOptions` though that is much less frequently used.

**Comment by dskarbek** [comment]
> The `Builder` can be converted to a `WorkflowServiceStubsOptions` to be logged 
So long as there's no failures that the build method will trigger on a partially filled out Builder.
