### ISSUE TITLE
It's impossible to send unset duration

### ISSUE THREAD

**Issue by Duzhinsky** [temporalio/sdk-java#2065]
## Expected Behavior

When `java.util.Duration` is `null` in an options class like `SchedulePolicy` it is treated as an unset value in a protobuf message _in some cases_

## Actual Behavior

`null` values are sent as zero duration. There was a TODO in the appropriate method about refactoring this behaviour, but was removed in #1950

https://github.com/temporalio/sdk-java/blob/ec18bc86d52f23add2dc97682d94c629e6282bf1/temporal-sdk/src/main/java/io/temporal/internal/common/ProtobufTimeUtils.java#L43-L48

## A problem 

I'm creating schedules using the following code:
```java
...
var policy = SchedulePolicy.newBuilder()
                .setOverlap(ScheduleOverlapPolicy.SCHEDULE_OVERLAP_POLICY_BUFFER_ONE)
                .build();
var schedule Schedule.newBuilder()
                .setAction(actionStartWorkflow)
                .setSpec(spec)
                .setPolicy(policy)
                .build();
```
Which causes sending `0` in the `catchupWindow` property of `SchedulePolicy`. Hence, server side treats it as `0` and uses `MinCatchupWindow` (=10 sec) instead of expected `DefaultCatchupWindow` (=1yr)

https://github.com/temporalio/temporal/blob/aca0d911a908b2584f4cffcc73425c5119dbe722/service/worker/scheduler/workflow.go#L750-L759

## Steps to Reproduce the Problem

  1. Create a schedule using the code above
  2. Check its catchupWindow

**Comment by Quinn-With-Two-Ns** [comment]
Most of time the Temporal server treats zero and unset durations the same, unfortunately it seems like schedules makes a distinction. Probably need to add conversion functions for that preserve null for time conversion.
