### ISSUE TITLE
Java SDK is not reporting workflow_failures from the code path via the FailWorkflowExceptionTypes

### ISSUE THREAD

**Issue by jlacefie** [temporalio/sdk-java#2103]
## Expected Behavior
Workflow Failed Cloud Metrics and Java SDK Metrics should "closely" match each other

## Actual Behavior
Workflow Failed metrics differ between Temporal Cloud and SDK metrics. 

## Steps to Reproduce the Problem
- NDE should typically get retried through WFT, I'm not sure what exactly happened to there WFs, but I'm aware we can force the Workflow exec failure by setting WorkflowImplementationOptions with .setFailWorkflowExceptionTypes(NonDeterministicException.class)
- This allowed me to reproduce the metric discrepancy between SDK's [workflow_failed](https://docs.temporal.io/references/sdk-metrics#workflow_failed) vs server/cloud's temporal_cloud_v0_workflow_failed_count, which seems to be the main concern.
- it appears Java SDK is not reporting workflow_failures from the code path via the FailWorkflowExceptionTypes
- The only place that SDK reports workflow_failures is from: https://github.com/temporalio/sdk-java/blob/v1.23.2/temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowExecutor.java#L97, which is not reachable when a workflow fails with WorkflowExecutionException from here: [https://github.com/temporalio/sdk-java/blob/v1.23.2/temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java#L2[…]60](https://github.com/temporalio/sdk-java/blob/v1.23.2/temporal-sdk/src/main/java/io/temporal/internal/replay/ReplayWorkflowRunTaskHandler.java#L256-L260)
## Specifications

  - Version:
  - Platform:
Temporal Cloud

**Comment by Quinn-With-Two-Ns** [comment]
Related to https://github.com/temporalio/sdk-java/issues/1590

**Comment by Quinn-With-Two-Ns** [comment]
Investigating this more the Java SDK does report `workflow_failures` correctly if the exception is throw in the user workflow code. The miss is when the exception is thrown by the SDK itself, which is often where `NonDeterministicException` are thrown.
