### ISSUE TITLE
Confirm non-utf8 proto string behavior

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-java#2106]
**Describe the solution you'd like**

In Go when we switched from gogoproto to common proto, we recognized that the former allowed invalid utf8 but not the latter. We have seen a potential case where a user _may_ have set invalid utf-8 in a proto `Failure` `message`. We need to confirm whether Java proto library even allows this (in either direction if possible, but especially at marshal time), and then assess our options.

**Comment by Quinn-With-Two-Ns** [comment]
Confirmed the java proto library does not allow non-utf8 proto string
