### ISSUE TITLE
Add option to configure the deadline of `ChannelManager#getServerCapabilities`

### ISSUE THREAD

**Issue by fextr** [temporalio/sdk-java#2132]
## Expected Behavior

When I [setRpcTimeout](https://github.com/temporalio/sdk-java/blob/abd9f2d1371a0355c01e85bc03763c79b1846ace/temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java#L774) in WorkflowServiceStubsOptions it overrides the deadline in [getServerCapabilitiesWithRetryOrThrow](https://github.com/temporalio/sdk-java/blob/abd9f2d1371a0355c01e85bc03763c79b1846ace/temporal-serviceclient/src/main/java/io/temporal/serviceclient/SystemInfoInterceptor.java#L95)

## Actual Behavior

I'm enforced to use deprecated [setHealthCheckAttemptTimeout](https://github.com/temporalio/sdk-java/blob/abd9f2d1371a0355c01e85bc03763c79b1846ace/temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java#L696) because it is still used in the [ChannelManager](https://github.com/temporalio/sdk-java/blob/master/temporal-serviceclient/src/main/java/io/temporal/serviceclient/ChannelManager.java#L327)

## Steps to Reproduce the Problem

1. Set `rpcTimeout` in `WorkflowServiceStubsOptions`.
2. Observe that it does not override the deadline in `getServerCapabilitiesWithRetryOrThrow`
3. Note the usage of the deprecated `healthCheckAttemptTimeout` in `ChannelManager`.

## Specifications

  - Version: Java SDK 1.24.0

**Comment by Quinn-With-Two-Ns** [comment]
`getServerCapabilities` is intentionally overriding the rpc timeout. If you need to configure a different deadline on  `getServerCapabilities` it would need to be a separate option.

**Comment by Quinn-With-Two-Ns** [comment]
Yes, it should be called `getSystemInfoTimeout` though `serverCapabilities` is just an internal name to the Java SDK.

**Comment by Quinn-With-Two-Ns** [comment]
Why do you need to configure the deadline on `getSystemInfo`?
