### ISSUE TITLE
Schedules without a catch up window use the min catch up window instead of the default catch up window

### ISSUE THREAD

**Issue by dcohen8128** [temporalio/sdk-java#2189]
## Expected Behavior
It's indicated in a few places that the default catch up window on a schedule is 1 year:
1. [The documentation website](https://docs.temporal.io/workflows#catchup-window)
2. [The proto definition](https://github.com/temporalio/api/blob/v1.37.0/temporal/api/schedule/v1/message.proto#L239)
3. [The server code](https://github.com/temporalio/temporal/blob/v1.24.2/service/worker/scheduler/workflow.go#L208)

So I would expect that if I don't set a catch up window on my `SchedulePolicy` when creating the schedule it will use the default value of 1 year.

## Actual Behavior
If you don't set a catch up window on the `SchedulePolicy` the SDK will turn that into a duration of 0 when converting it into the proto `Duration` object [here](https://github.com/temporalio/sdk-java/blob/v1.24.3/temporal-sdk/src/main/java/io/temporal/internal/common/ProtobufTimeUtils.java#L76-L85). Then on the server the it will see that 0 is lower than the 10 second `minCatchupWindow` and use the min instead [here](https://github.com/temporalio/temporal/blob/v1.24.2/service/worker/scheduler/workflow.go#L1149).

## Steps to Reproduce the Problem
Create a schedule with a policy that does not contain a catch up window:

```java
var policy = SchedulePolicy.newBuilder()
        .setCatchupWindow(null) // Or, remove this line since null is the default
        .build();

var schedule = Schedule.newBuilder()
        /* set action and spec and whatever else you want */
        .setPolicy(policy)
        .build();

var handle = scheduleClient.createSchedule("ScheduleId", schedule, ScheduleOptions.newBuilder().build());
```

## Specifications

  - Version: As far as I can tell, all versions since Schedules were released (Server - 1.17.0+, Java SDK - 1.20.0+)
  - Platform:

**Comment by Quinn-With-Two-Ns** [comment]
This behaviour was changed in https://github.com/temporalio/sdk-java/commit/9a856f30 which is included in Java SDK 1.24.0+

**Comment by dcohen8128** [comment]
Oh cool, we have a bunch of systems using older versions so that's what I had dug through. My fault for not checking the whole data flow in the newer version.

**Comment by dcohen8128** [comment]
For existing schedules can we do a no-op update to remove the 0 value from the policy?

**Comment by Quinn-With-Two-Ns** [comment]
Yes you can update the schedule with new policy to remove to remove the value
