### ISSUE TITLE
Thread `LocalActivitySlotSupplierQueue` prevent JVM from termination

### ISSUE THREAD

**Issue by nikoncode** [temporalio/sdk-java#2194]
# Steps to reproduce 

* use `spring.temporal.start-workers = false` or just don't start worker
* terminate application (`io.temporal.worker.WorkerFactory#shutdown`)  - `LocalActivitySlotSupplierQueue` remains working and blocks jvm from exiting

Reproduced on last available temporal version 1.25.0

# Possible explanation

* `io.temporal.internal.worker.LocalActivitySlotSupplierQueue#LocalActivitySlotSupplierQueue` created during initialization of `io.temporal.internal.worker.LocalActivityWorker#LocalActivityWorker`
* `io.temporal.internal.worker.LocalActivityWorker#activityAttemptTaskExecutor` became null until `start` called - we don't do this
* `io.temporal.internal.worker.LocalActivityWorker#shutdown` expect `activityAttemptTaskExecutor` to be not null and doesn't call  `slotQueue.shutdown()`

# Possible fix
* Since this thread created in constructor we should probably move `slotQueue.shutdown()` one line higher to stop this thread indepenendly of worker start call.
* Or initialize it in start, not in the constructor.

# Use cases 

We want to have support of "management commands" inside our applications. This is separate run mode, which requires disable of all external services (kafka, Temporal, grpc, etc).

**Comment by nikoncode** [comment]
Snippet to reproduce:

```
        WorkflowServiceStubs service = WorkflowServiceStubs.newLocalServiceStubs();
        WorkflowClient client = WorkflowClient.newInstance(service);
        WorkerFactory factory = WorkerFactory.newInstance(client);
        Worker worker = factory.newWorker("test");

        factory.shutdown();
```

**Comment by nikoncode** [comment]
It's also strange that `io.temporal.internal.worker.LocalActivityWorker#shutdown` call interrupt for this thread conditionally, but `io.temporal.internal.worker.LocalActivityWorker#awaitTermination` not.

**Comment by Quinn-With-Two-Ns** [comment]
Thank you for the detailed bug report:
* `LocalActivitySlotSupplierQueue` should only create a thread if the worker is started
* `awaitTermination` should not call `slotQueue.shutdown()`, but should verify the shutdown has finished. If the queue was never started it can return immediately
