### ISSUE TITLE
`Workflow.newUntypedActivityStub` does not inherit default options the same way `Workflow.newActivityStub` does

### ISSUE THREAD

**Issue by idubrov** [temporalio/sdk-java#2200]
## Expected Behavior

Expected both of the following stubs to use the same default options configured via Spring Boot bean implementing `TemporalOptionsCustomizer<WorkflowImplementationOptions.Builder>`.

```
var stub = Workflow.newActivityStub(Whatever.class, null); // no explicit options provided
var untypedStub = Workflow.newUntypedActivityStub(null); // no explicit options provided
```

## Actual Behavior

The first one does use the default options, via this line: https://github.com/temporalio/sdk-java/blob/1a054bb93401ec921b5a0ac0be3b2fd2c387db51/temporal-sdk/src/main/java/io/temporal/internal/sync/WorkflowInternal.java#L316

However, the second one does not. Not sure if this is intentional or not (I noted that I _have_ to pass `options` argument to the `newUntypedActivityStub`), but this was a bit surprising behavior -- I configure default options so I can override them via Spring properties, and my untyped stub was not picking them (I was able to retrieve them via `WorkflowInternal.getRootWorkflowContext().getDefaultActivityOptions()`, but with some package-hacking as this API is internal).

## Specifications

  - Version: 1.25.1

**Comment by Quinn-With-Two-Ns** [comment]
Yes this is intentional `setDefaultActivityOptions` specifies it only applies to `newActivityStub` in general the activity interface is required to construct the final default activities options .
