### ISSUE TITLE
Support actual versions of spring boot

### ISSUE THREAD

**Issue by mvkirillov** [temporalio/sdk-java#2256]
Good afternoon, tell me, will you support compatibility with current versions of Spring Boot, for example 3.2.x, 3.3.x?

**Comment by Quinn-With-Two-Ns** [comment]
The Springboot integration supports 3.x, see our springboot [sample](https://github.com/temporalio/samples-java/blob/main/gradle.properties#L3). 

For user support questions please use our [forum](https://community.temporal.io/) or [slack](https://t.mp/slack). We use github for bugs and feature requests.

**Comment by mvkirillov** [comment]
io.temporal:temporal-spring-boot-starter:1.25.0
compiled for spring boot 2.7.18 version

Updating the version in the file to 3.2 does not update the version in application

**Comment by mvkirillov** [comment]
I set springBootPluginVersion=3.2.0
but when i start TemporalSpringbootSamplesApplication spring boot has version 2.7.18 (first log with banner)
