### ISSUE TITLE
WorkflowLock.tryLock should not create a timer if the lock is available

### ISSUE THREAD

**Issue by smax48** [temporalio/sdk-java#2350]
When there's a call to `WorkflowLock.tryLock(timeout, condition)` , even if the lock is available - a new timer is created and saved to WF history (which can potentially affect performance and probably costs in temporal cloud)

Is there any particular reason that this method doesn't try to short-circuit execution (i.e. do not call `Workflow.await`) if the lock is already available (so unblock condition is already true)?...

This is actually a general question for `Workflow.await` as well ...

**Comment by mfateev** [comment]
I agree that `Workflow.await` shouldn't create a timer ifthe  condition is immediately satisfied.

**Comment by Quinn-With-Two-Ns** [comment]
> I agree that Workflow.await shouldn't create a timer if the condition is immediately satisfied.

Second, there is already another open [issue](https://github.com/temporalio/sdk-java/issues/2312) that will cover this change.

**Comment by Quinn-With-Two-Ns** [comment]
Closing as a duplicate because there is already an issue to track the change to `Workflow.await`
