### ISSUE TITLE
PollActivityTaskQueue should return empty poll after a minute

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#248]
**Is your feature request related to a problem? Please describe.**
Service returns an empty poll after a minute if no tasks are available. The test service[ never returns an empty poll](https://github.com/temporalio/sdk-java/blob/30420212a26283cf7cbe6339512058a3186074e8/temporal-sdk/src/main/java/io/temporal/internal/testservice/TestWorkflowStoreImpl.java#L365), blocking until a task is available. It causes gRPC level request timeouts which while benign look scary.

**Describe the solution you'd like**
Return an empty poll after a minute.

**Comment by Spikhalskiy** [comment]
Closed by ##713
