### ISSUE TITLE
Add opentracing context propagator

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#258]
https://github.com/uber/cadence-java-client/pull/478

**Comment by bowsersenior** [comment]
Since opentracing is now part of [opentelemetry](https://opentelemetry.io), it would be great if you could check that the new context propagator will work with opentelemetry as well.

**Comment by Spikhalskiy** [comment]
This can be closed. It's addressed in https://github.com/temporalio/sdk-java/pull/418
