### ISSUE TITLE
Add WorkflowTest Rule

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#259]
**Is your feature request related to a problem? Please describe.**
WorkflowTestEnvironment requires setup and tear down as well as `globalTimeout` and `watchman` setup in each tested class to support troubleshooting.

**Describe the solution you'd like**
Create `@WorkflowTest` rule that would encapsulate all of these to simplify code.

**Additional context**
[HelloAsyncLambdaTest](https://github.com/temporalio/samples-java/blob/76713f24490a0cec2a0ead458f3c5a4a0a56bf83/src/test/java/io/temporal/samples/hello/HelloAsyncLambdaTest.java) that sets both timeout and watchman.

**Comment by vitarb** [comment]
We need to make test workflow environment that works with docker service.
There is a lot of setup code that we can simplify.

**Comment by vitarb** [comment]
Addressed as part of https://github.com/temporalio/sdk-java/pull/286
