### ISSUE TITLE
Was io.temporal.testing.TestWorkflowEnvironment removed with 1.0.4?

### ISSUE THREAD

**Issue by darewreck54** [temporalio/sdk-java#334]
I upgraded the java sdk to 1.0.5via `implementation('io.temporal:temporal-sdk:1.0.5');` and I got the following error:

```
error: package io.temporal.testing does not exist
import io.temporal.testing.TestWorkflowEnvironment;
```

Did it get removed?

## Expected Behavior
Update to 1.0.5 without my test breaking

## Actual Behavior
an exception get thrown
```
error: package io.temporal.testing does not exist
import io.temporal.testing.TestWorkflowEnvironment;
```

If i revert back to 1.0.4 I don't have the issue.

THanks,
Derek

**Comment by GreyTeardrop** [comment]
All test support code including `TestWorkflowEnvironment` was moved to the `temporal-testing` module in the 1.0.5 release (see PR: https://github.com/temporalio/sdk-java/pull/292).

**Comment by darewreck54** [comment]
k thanks.  What might be helpful is have a change log that points out "Breaking Change" and then point out that users need to include a new package.
