### ISSUE TITLE
Log messages emitted by POJOActivityTaskHandler should include workflow ID and run ID

### ISSUE THREAD

**Issue by rfwagner** [temporalio/sdk-java#353]
We are seeing logs emitted by this line in POJOActivityTaskHandler:

      log.warn(
          "Activity failure. ActivityId="
              + info.getActivityId()
              + ", activityType="
              + info.getActivityType()
              + ", attempt="
              + info.getAttempt(),
          e);

Unfortunately there is no out-of-the-box way to search for a workflow by activity ID - neither in the UI or via the CLI.

It would be ideal if all messages emitted by POJOActivityTaskHandler included the workflow ID and run ID. Since these fields are members of the ActivityInfo interface, I assume this would be very easy to add in this particular case.

Perhaps it would be worth taking a pass through the entire SDK and add workflow ID and run ID to all log lines where it is easy to do so?

**Comment by mfateev** [comment]
The workflowID and runID are already part of [MDC](https://github.com/temporalio/sdk-java/blob/f7bc07dfe69441cbdaf3a4697ab3fab713324d45/temporal-sdk/src/main/java/io/temporal/internal/worker/ActivityWorker.java#L183). Change your log format to include MDC fields.

**Comment by vitarb** [comment]
@rfwagner look [here](https://www.baeldung.com/mdc-in-log4j-2-logback) for examples of how to configure MDC fields for different loggers.
