### ISSUE TITLE
Default WorkflowIdReusePolicy is AllowDuplicate and not AllowDuplicateFailedOnly

### ISSUE THREAD

**Issue by kartikv11** [temporalio/sdk-java#361]
## Expected Behavior
Default WorkflowIdReusePolicy should be AllowDuplicateFailedOnly as per [documentation](https://docs.temporal.io/docs/workflows/?_ga=2.1788337.1425639198.1614084660-706488885.1612797794#id-uniqueness)

## Actual Behavior
Default WorkflowIdReusePolicy is AllowDuplicate instead

## Steps to Reproduce the Problem

  1.Create a Workflow and let it complete
  1.Create another workflow with same id as Workflow from Step 1
  1.Both workflows get processed

## Specifications

  - Version: 1.0.5
  - Platform: java

**Comment by Quinn-With-Two-Ns** [comment]
current dev guid and java docs says `AllowDuplicate` is the default

https://docs.temporal.io/workflows?_ga=2.1788337.1425639198.1614084660-706488885.1612797794#workflow-id-reuse-policy
