### ISSUE TITLE
Connection management issues with Java SDK

### ISSUE THREAD

**Issue by kelnos** [temporalio/sdk-java#362]
## Expected Behavior

When I re-deploy my Temporal cluster, I expect workers and workflow run initiators to not even notice that the topology of the cluster has changed, or that some hosts have gone away and others have reappeared.  Any connection failures due to these changes should be transparently "fixed up" by the SDK.

## Actual Behavior

During cluster deployments I see timeouts and periods of unavailability (with many log error messages with the GRPC `UNAVAILABLE` error in the activity poller).  Sometimes workflow run invocations fail as well with timeout errors.

## Steps to Reproduce the Problem

  1. Build a temporal cluster with, say, 6 nodes. 
  1. Add some worker nodes implementing a simple workflow, set up to invoke the workflow fairly often, like once every 5 seconds.
  1. Redeploy the entire Temporal cluster.  (In our case, we do a rolling deploy, where we put a new node in, wait for it to join the cluster [checking by polling the cluster metadata endpoint], wait an additional 2 minutes to allow things to settle, and then take the old node out.)
  1. Watch metrics/logs on the worker nodes, and notice errors in the worker/activity pollers, as well as some failures to start workflows.

## Specifications

  - Version: 1.0.5
  - Platform: Linux x86_64

## More Information

Our network topology uses a service mesh sidecar to communicate between hosts.  A Temporal worker (or workflow-run-invoker) is instructed to talk to Temporal by connecting to a port on localhost that is backed by [Envoy](https://www.envoyproxy.io) running in HTTP2 mode.  Envoy will then (over HTTP2+TLS) connect to Envoy running on the Temporal server, which will then connect to the Temporal server itself (again using HTTP2).

In order to accommodate low-traffic workers, initially server-to-server and client-to-Envoy timeouts were set very long, on the order of 10 minutes.  However, that caused up to 10 minute periods of unavailability during deployments.  More recently I have dropped the timeouts down to 65 seconds, and have instructed Envoy to retry transparently on GRPC `UNAVAILABLE` and `DEADLINE-EXCEEDED` errors.  However, we still see intermittent failures during Temporal cluster deployments.

On the workers, we have left all the default timeouts alone in the Temporal client (as they seem fairly sane and short).

**Comment by kelnos** [comment]
Some logs with stack traces:
```
io.grpc.StatusRuntimeException: UNAVAILABLE: transport is closing
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc.pollWorkflowTaskQueue(WorkflowServiceGrpc.java:2658)
	at io.temporal.internal.worker.WorkflowPollTask.poll(WorkflowPollTask.java:77)
	at io.temporal.internal.worker.WorkflowPollTask.poll(WorkflowPollTask.java:37)
	at io.temporal.internal.worker.Poller.run(Poller.java:273)
	at io.temporal.internal.worker.Poller.run(Poller.java:242)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
and
```
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156)
	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc.pollWorkflowTaskQueue(WorkflowServiceGrpc.java:2658)
	at io.temporal.internal.worker.WorkflowPollTask.poll(WorkflowPollTask.java:77)
	at io.temporal.internal.worker.WorkflowPollTask.poll(WorkflowPollTask.java:37)
	at io.temporal.internal.worker.Poller.run(Poller.java:273)
	at io.temporal.internal.worker.Poller.run(Poller.java:242)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by vitarb** [comment]
There are two potential issues that can cause this:
1. gRPC backoff keeps increasing if the underlying backend is unavailable and can go up to 2 minutes per retry. We've addressed this by periodically resetting gRPC backoff every 10 seconds.
2. Connections are abruptly closed on the server side and client things that they are still active until TCP timeout occurs. For this issue, in the latest release (1.0.6), we've added simple connection management improvement in #351 which would re-establish connections to the server periodically. Also we've added a keep-alive checking on the client side, but it is currently disabled by default as server doesn't have keep-alive friendly configuration yet. Feel free to experiment with the configuration though (see #367 for the list of config parameters).

**Comment by kelnos** [comment]
Great, thank you @vitarb!  We'll be upgrading and doing some experiments over the next couple days.

**Comment by kelnos** [comment]
Ok, we've tried 1.0.6 and enabled the keepalive (with a 30 second interval), and things do definitely seem to be better.  We've been unable to repro the issue (so far) with new workflow run invocations failing, though we still do see a bit of log noise from the activity poller threads.  It does appear that all workflows and activities do end up getting run, though I don't have numbers yet on if there's any increase in latency.

**Comment by kelnos** [comment]
Things have been a lot better over the past few weeks, and we've gone through several Temporal cluster deployments without incident.  We've been using the keepalive mechanism with a 30-second ping.

One thing that has been a bit frustrating is that the [logging in Poller.java](https://github.com/temporalio/sdk-java/blob/v1.0.6/temporal-sdk/src/main/java/io/temporal/internal/worker/Poller.java#L70) is causing our pagers to go off, even though the poller reestablishes its connection and recovers on its own.  We end up with 15-20 instances of this error message[0] logged per worker host during the cluster deployment (some coming from `WorkflowPollTask` and some coming from `ActivityPollTask`).

I've considered adding custom rules to avoid paging in this case, but anything I can come up with feels brittle (and also possibly not safe, and could mask real issues), and these custom rules would have to be manually applied to every new service that starts using Temporal.

I think what would help us most is if the logging logic could log at `WARN` for an issue that could be transient, and then only escalate to `ERROR` if it's unable to re-establish a connection within a reasonable amount of time.  (In general we only page for some smallish number of occurrences of `ERROR` logs; some teams do page for `WARN`s but only in cases where there are a significantly large number of them.)

[0] We see several different exception messages on this:
* `UNAVAILABLE: upstream connect error or disconnect/reset before headers. reset reason: connection termination`
* `UNAVAILABLE: transport is closing`
* `DEADLINE_EXCEEDED: deadline exceeded after 69.999973290s. [remote_addr=127.0.0.1/127.0.0.1:17233]`
* `UNAVAILABLE: Network closed for unknown reason`
* `UNAVAILABLE: Subchannel shutdown invoked`
