### ISSUE TITLE
When a workflow task fails and the workflow is still running, cancel request doesn't seem to work

### ISSUE THREAD

**Issue by darewreck54** [temporalio/sdk-java#371]
I have a case where I'm not able to cancel the workflow.  The workflow itself experience a workflowTaskFail but keeps running infinitely since no timeout was specified which the UI marks as runnings.  When I try to send a request to cancel the workflow, the request return a 204 but the workflow is never canceled and is still running.  However, if i start a new workflow, the same request will actually cancel the workflow.

Below is a screen shot of the workflow history where you can see the results.

![image](https://user-images.githubusercontent.com/16171726/109483919-a4ff1280-7a34-11eb-8ddb-7ac88928f108.png)

## Expected Behavior
I expect that the workflow would cancel if it returns a 204

## Actual Behavior
Request returns a 204 but never cancels.

## Steps to Reproduce the Problem
1) Have a workflowTask fail
2) Try to cancel the workflow
 
## Specifications

  - Version:
  - Platform:

**Comment by samarabbas** [comment]
Can you share the complete `failure` message in screen shot above.  Also please also share the entire workflow execution history for this run.
Looks like the workflow task is failing most likely due to either workflow implementation logic or might be due to some java sdk issue.  Once the workflow execution goes into this state then workflow cancellation will not work as it requires the workflow task to be successfully processed.  In this situation if you want to stop the workflow execution then your only option is to `Terminate` it.

**Comment by darewreck54** [comment]
```
io.temporal.internal.replay.InternalWorkflowTaskException: Failure handling event 10 of 'EVENT_TYPE_WORKFLOW_TASK_STARTED' type. IsReplaying=false, PreviousStartedEventId=10, workflowTaskStartedEventId=10, Currently Processing StartedEventId=10 
io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:193)
io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleEvent(ReplayWorkflowRunTaskHandler.java:140)
io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:180)
io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTask(ReplayWorkflowRunTaskHandler.java:150)
io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithEmbeddedQuery(ReplayWorkflowTaskHandler.java:201)
io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:114)
io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:314)
io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:280)
io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

Caused By: java.lang.RuntimeException: WorkflowTask: failure executing SCHEDULED->WORKFLOW_TASK_STARTED, transition history is [CREATED->WORKFLOW_TASK_SCHEDULED] 
io.temporal.internal.statemachines.StateMachine.executeTransition(StateMachine.java:140)
io.temporal.internal.statemachines.StateMachine.handleHistoryEvent(StateMachine.java:91)
io.temporal.internal.statemachines.EntityStateMachineBase.handleEvent(EntityStateMachineBase.java:63)
io.temporal.internal.statemachines.WorkflowStateMachines.handleEventImpl(WorkflowStateMachines.java:210)
io.temporal.internal.statemachines.WorkflowStateMachines.handleEvent(WorkflowStateMachines.java:178)
io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleEvent(ReplayWorkflowRunTaskHandler.java:140)
io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:180)
io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTask(ReplayWorkflowRunTaskHandler.java:150)
io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithEmbeddedQuery(ReplayWorkflowTaskHandler.java:201)
io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:114)
io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:314)
io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:280)
io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
java.lang.Thread.run(Thread.java:748)

Caused By: java.lang.NullPointerException: type is marked non-null but is null 
....
```

What is the proper way to deal with exceptions thrown  in your workflow entry point?  It looks like i need to throw a specific type of exception so that temporal knows how to put it in a state taht can be canceled?

**Comment by vitarb** [comment]
What is the stack trace for the last NullPointerException? Is it happening in your workflow code?

**Comment by darewreck54** [comment]
@vitarb the stack trace is specific to my workflow code where a value was null when it shouldn't be.  I'm wondering how I'm suppose to properly handle it, so that the workflow will fail automatically without forcing me to send at terminate command

**Comment by mfateev** [comment]
By default NPE (as well as any unknown exception) will cause the workflow to get stuck. This is to give you chance to find the bug and fix it through a new deployment. If you want your workflow to fail on all exceptions specify it through  WorkflowImplementationOptions.failWorkflowExceptionTypes:
```java
    worker.registerWorkflowImplementationTypes(
        WorkflowImplementationOptions.newBuilder()
            .setFailWorkflowExceptionTypes(Throwable.class)
            .build(),
        <YourWorkflowClass>.class);
```

**Comment by darewreck54** [comment]
thanks! @mfateev

**Comment by darewreck54** [comment]
Just thinking out loud here.  In the case a user wants to trouble shoot, after a new deployment would you `replay` which would start from where it left off?  However, if there is something wrong with the inputs into the workflow then the only solution would to start the workflow with the correct input?  Does that sound correct?

**Comment by mfateev** [comment]
Yes, you cannot change inputs after the workflow has started.
