### ISSUE TITLE
API docs erroneously claim WorkflowIdReusePolicy default is AllowDuplicateFailedOnly

### ISSUE THREAD

**Issue by skrul** [temporalio/sdk-java#387]
## Expected Behavior

According to maxim, the default is `AllowDuplicate`

## Actual Behavior

Docs say default is `AllowDuplicateFailedOnly`

## Steps to Reproduce the Problem

check the docs:
https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/client/WorkflowOptions.java#L134

## Specifications

  - Version: v1.0.6

**Comment by Spikhalskiy** [comment]
Closed by #1307
