### ISSUE TITLE
Prohibit use of WorkflowClient and Activity interfaces in workflow code.

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#402]
**Is your feature request related to a problem? Please describe.**
New users might not be aware of nondeterministic requirements and might use WorkflowClient and Activity interfaces from the workflow code.

**Describe the solution you'd like**
Add explicit checks that throw exceptions from WorkflowClient and Activity APIs if they are called from workflow threads.

**Comment by Spikhalskiy** [comment]
Usage of `WorkflowClient`, `ActivityCompletionClient`, and `WorkflowServiceStubs` was prohibited from workflow thread and code.
If some of the application developers encounter backward compatibilities problems with this change they can disable this check by setting environment variable `TEMPORAL_DISABLE_NON_WORKFLOW_CODE_ENFORCEMENTS` to "true". This option shouldn't be used by any new code and left only to provide backward compatibility for INCORRECTLY implemented legacy workflow implementations.
