### ISSUE TITLE
Workflow#newActivityStub(activityInterface) method produces broken activity stubs

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#413]
ActivityOptions has a requirement that either `startToClose` or `scheduleToClose` has to be defined. ActivityOptions doesn't have any defaults for both of them at the same time. So default ActivityOptions is actually invalid. 

`Workflow#newActivityStub` has two versions: `Workflow#newActivityStub(activityInterface)` and `Workflow#newActivityStub(activityInterface, activityOptions)`. The first version without `activityOptions` param produces an Activity stub with default broken ActivityOptions, so this method never really can be used right now.

**Comment by vitarb** [comment]
On one hand, since activities are very use case specific, I imagine, it would be hard to pick the "right" value, but on on the other I agree that having invalid default options is bad experience. @mfateev what do you think? Should we set schedule to close to something like 10 seconds by default?

**Comment by Spikhalskiy** [comment]
Also probably if we enforce "`startToClose` or `scheduleToClose`" rule, ActivityOptions#Builder#validateAndBuildWithDefaults should throw an exception when both of them are not initialized.

**Comment by vkoby** [comment]
There is no good default value for these timeouts and you can now set default activity options through WorkflowImplementationOptions. But good point about throwing an exception when they haven't been set.
