### ISSUE TITLE
Workflow retry after Activity failure works incorrectly with TestService

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#414]
## Expected Behavior

We have a simple workflow that triggers an activity that fails on its first invocation and succeeds on subsequent calls.
We setup Activity#retryOptions into maxAttempt = 1 and Workflow#retryOptions into maxAttempt = 2.
We expect the workflow to pass after the second run.

## Actual Behavior

Workflow fails in unit tests, there is no second run of the workflow.

## Steps to Reproduce the Problem
The following unit test is failing, while expected to pass:
https://github.com/Spikhalskiy/java-sdk/commit/3ff42f47a9a0c4da359cec07d6cccccf808e6836#diff-1cfa937ab805ee84ebdaf1e67c2f920b3ad72d53cf29e560061aeee0f3d7e012R91
 
If uncomment `//.setUseExternalService(true)` the test passes which points that the issue is probably in TestService implementation.

## Specifications

Current master: 8384e5393eb84be3044fced0b3db3daa8749c75f

**Comment by vitarb** [comment]
Thanks for reporting the issue, we'll take a look and will get back to you.
