### ISSUE TITLE
Allow passing proxy objects to registerActivitiesImplementations 

### ISSUE THREAD

**Issue by mostafacs** [temporalio/sdk-java#466]
I'm implementing a quarkus extension for temporal and it's about 90% completed. I want to support quarkus interceptors in Activities. quarkus handle interceptor interceptions with Proxy and Invocation Handler

I think supporting a factory method and passing the activity interface too is the solution

This is the link for my extension: https://github.com/mostafacs/quarkus-temporal-extension

**Comment by mfateev** [comment]
Have you considered using [DynamicActivity](https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/activity/DynamicActivity.java)?
