### ISSUE TITLE
Allow configuration of workers to back off completely if the server is not available

### ISSUE THREAD

**Issue by eminn** [temporalio/sdk-java#481]
**Is your feature request related to a problem? Please describe.**
I want the workers to stop trying to connecting to the server if the server is not available using `WorkflowServiceStubsOptions`

**Describe the solution you'd like**
I'd like to configure workers to stop polling/trying to connecting to the server if the server is not available after a specified time period.

**Describe alternatives you've considered**
N/A

**Additional context**
Slack discussion https://temporalio.slack.com/archives/CTT84KXK9/p1620663515093300

**Comment by Spikhalskiy** [comment]
> workers to stop polling/trying
I don't think stat "stopping" is the right semantic here. We still want them to reconnect when the network or the server is back. But it would be good to expose backoffCoefficient for workers.
Also, it would be great to expose backoffCoefficient for client stubs too as we discussed here: 
https://github.com/temporalio/sdk-java/pull/472/files#r627959282

**Comment by vkoby** [comment]
Please take a look at [PollerOptions.java#L54](https://github.com/temporalio/sdk-java/blob/23bccf07d54982dd3048ab32f06c06c4811e74ce/temporal-sdk/src/main/java/io/temporal/internal/worker/PollerOptions.java#L54). We currently have default values for 
`pollBackoffCoefficient = 2`
`pollBackoffInitialInterval = 100ms`
`pollBackoffMaximumInterval = 1m`
In the end, the worker will keep polling the server every minute, which should be fine in most cases.
Does this work for you?

**Comment by eminn** [comment]
@vkoby In my case I'd need to stop them to fail a k8s deployment as keeping the workers running and letting them try to connect non-existing server would create a lot of noise in terms of logging. This way I don't need to implement a custom health check logic (e.g. checking the namespace exists), the workers will die after configured time or attempt count passes.

**Comment by vkoby** [comment]
@eminn Will implement health check. This has already been done in Go SDK see [client.go#L417](https://github.com/temporalio/sdk-go/blob/cea0147023cc324a8adce606d608cb7298e6cfcb/internal/client.go#L417)
