### ISSUE TITLE
Make DEFAULT_DEADLOCK_DETECTION_TIMEOUT configurable

### ISSUE THREAD

**Issue by skrul** [temporalio/sdk-java#503]
**Is your feature request related to a problem? Please describe.**

We have a custom data converter that can get a little slow due to certain cluster conditions and we sometimes trip over this 1s timeout.

**Describe the solution you'd like**

Make DEFAULT_DEADLOCK_DETECTION_TIMEOUT configurable, see https://github.com/temporalio/sdk-java/blob/master/temporal-sdk/src/main/java/io/temporal/internal/sync/DeterministicRunner.java#L37

**Describe alternatives you've considered**

Forking 😅

**Comment by vitarb** [comment]
Yes, I agree we should do it. Let's add a new worker option.
