### ISSUE TITLE
Add pollExecutor thread pool metrics

### ISSUE THREAD

**Issue by robzienert** [temporalio/sdk-java#535]
**Is your feature request related to a problem? Please describe.**
It's currently unclear the SDK's thread usage, as no thread pools are reporting their metrics. This makes it more difficult to tune workers.

**Describe the solution you'd like**
Adding a scheduled thread to get snapshot metrics on the thread pool's core, active, and max sizes would help. A synthetic "blocked" tasks metric may also be useful via subtracting `taskCount - completedTaskCount`.

What I'm unclear about is how to correctly tag these metrics. `Poller` has an `identity`, but as best as I can tell this is going to be different per-process so tracking how thread pool usage changes through application deployments would be impossible. Is there a good option here where pollers could get a deterministic name to reference them by for use in metric tags?

**Comment by robzienert** [comment]
@vitarb I could use your opinion on implementation here...

I believe I need to introduce either: A) An identity naming schemes, or B) A new `identityGroup` property for `WorkflowClientOptions`. Right now the `identity` defaults to `ManagementFactory.getRuntimeMXBean().getName()`, which make sense since we want all pollers to have unique identifiers. However, for the purposes of tracking metrics, we want an identifier that will stay consistent across processes and new worker deployments to correlate metrics.

Do you have a preference on which path to take? I think adding a new property (such as `identityGroup`) would be the most unobtrusive path forward for existing SDK users. This property would be nullable and default to `null`. In which case, the thread pool monitoring would not add a `group` tag.

Thoughts?

**Comment by Spikhalskiy** [comment]
@robzienert as we discussed, please use a ```WorkflowClientOptions#identity``` to identify a specific worker.

**Comment by robzienert** [comment]
My question is not about identifying a single worker, which `identity` is perfectly suited for. My question is identifying a group of like-workers, across processes. Here's an example:

Let's say we have an autoscaling group of workers, named `myworker-v000`. There are 3 EC2 instances inside of it, all of them using the same AMI, and so also configured exactly the same. In this case, there will be 3 unique `identity` values for each worker: This is desirable.

Now let's say I deploy a new version of my workers, named `myworker-v001`. These workers will still be doing the same thing, but with potentially new workflow / activity code. These will also all get new `identity` values: This is also desirable.

What is missing is a metric scope tag that will allow me to correlate the thread pools of these worker pollers between processes within the same ASG, as well as correlate the thread pools _across_ ASGs as the software changes. For this, I'm proposing that a new field called `identityGroup` is added, this field is _not unique_ and would be static across all processes and autoscaling groups. It would provide SDK users a means of understanding thread pool usage changes as code changes. Without such a tag, what I'm describing is impossible if there is more than 1 poller in the process.

**Comment by Spikhalskiy** [comment]
Rob was able to solve the problem with the APIs and abilities Temporal provides now.
Feel free to reopen any time if something is lacking.
