### ISSUE TITLE
Make `TEMPORAL_DEBUG` definable via code

### ISSUE THREAD

**Issue by robzienert** [temporalio/sdk-java#588]
**Is your feature request related to a problem? Please describe.**
Java does not let you modify environment variables from code like many other languages do (without doing a ton of reflection). This makes debugging workflows from tests annoying using editors like IntelliJ, as you need to create custom run configurations for each test that you want to debug. This is disruptive, and quickly clutters up the project's run configurations.

**Describe the solution you'd like**
Make `TEMPORAL_DEBUG` definable via code while setting up either the workflow client (or whatever), or optionally, via the Junit4/5 extensions. Something like:

```kotlin
val workflowExtension = TestWorkflowExtension.newBuilder()
  .setDebug(true)
  // ...
  .build()
```

**Describe alternatives you've considered**

1. Create a new `Run Configuration` for each test you want to debug. Outlined why this isn't desirable above.
2. Add `TEMPORAL_DEBUG=1` to the Gradle's `test` task. This is undesirable because then `TEMPORAL_DEBUG=1` will be set for all tests all of the time, opening up the potential for the deadlock detector to not catch obvious errors during tests.

**Comment by vitarb** [comment]
Have you tried setting this env var for all test configurations by default?
For example in intellij you can do it for the entire junit template:
![Screenshot from 2021-07-14 23-44-02](https://user-images.githubusercontent.com/1311694/125741635-d99b8513-1d3e-4176-ab31-e6c389a1f7f1.png)

**Comment by robzienert** [comment]
Yeah, that's possible, but then we'd have to wait for CI to get feedback of whether or not the deadlock detector gets hit, which has potential for wasted productivity cycles.

**Comment by vitarb** [comment]
Have you tried using `WorkerOptions.Builder#setDefaultDeadlockDetectionTimeout`? If you change that value in tests, it would override default timeout for the deadlock detector. Would that be sufficient for you?

**Comment by robzienert** [comment]
Oh, I totally missed that config option - yes, that would suit our needs fine. Thanks!
