### ISSUE TITLE
Allow context propagator to be set on LocalActivityOptions

### ISSUE THREAD

**Issue by ravikrn13** [temporalio/sdk-java#600]
## Expected Behavior
Users should be able to add custom ContextPropagators to LocalActivityOptions just like ActivityOptions.

## Actual Behavior
LocalActivityOptions does not have a list of context propagators and users are unable to add custom ContextPropagators.

## Steps to Reproduce the Problem

  1. Create a LocalActivityOption using builder
  2. Implement a ContextPropagator.
  3. Try to set the new ContextPropagator to LocalActivityOption.

## Specifications

  - Version: 1.0.9
  - Platform: sdk-java

**Comment by Spikhalskiy** [comment]
It's a duplicate of https://github.com/temporalio/sdk-java/issues/490

Please see a resolution here describing why we decided that it's not something we want to implement. Please use WorkerOptions#contextPropagators instead.
