### ISSUE TITLE
Automate pre-release SDK testing against samples-java & canary-java

### ISSUE THREAD

**Issue by vkoby** [temporalio/sdk-java#607]
**Is your feature request related to a problem? Please describe.**
Currently we run a snapshot of prerelease against [samples-java](https://github.com/temporalio/samples-java) & [canary-java](https://github.com/temporalio/canary-java) manually.

**Describe the solution you'd like**
Automate.

**Comment by Spikhalskiy** [comment]
It's an internal infrastructure related issue, please move to Notion.
