### ISSUE TITLE
a load balancer with an idle timeout causes java sdk to log UNAVAILABLE errors

### ISSUE THREAD

**Issue by thewmo** [temporalio/sdk-java#618]
## Expected Behavior

If the Temporal front-end server is behind a load balancer, and that load balancer should close an idle connection that is polling for tasks, if anything is logged it should be at a debug or info level, and the SDK should immediately create a new connection to resume the poll.

## Actual Behavior

sdk-java logs the following exception at level ERROR:

`io.grpc.StatusRuntimeException: UNAVAILABLE: unavailable\n	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.39.0.jar!/:1.39.0
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.39.0.jar!/:1.39.0
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.39.0.jar!/:1.39.0`

These clutter the logs and the only way to squelch them is to basically turn off all logging from the Poller logger. I have observed no functionality problems with this application, and the Poller appears to immediately resume a poll after this happens, so I don't think there are any functional problems here beyond the log spam.

## Steps to Reproduce the Problem

These steps correspond to the configuration in which I am observing the issue.

  1. Deploy temporal in AWS, in my case it is on ECS using the all-in-one docker image but the deployment method shouldn't matter.
  2. Configure an AWS ALB with http/2 GRPC support enabled pointing at the Temporal front-end endpoint. Set the idle-timeout of the ALB to some specific value in the range of several minutes.
  3. Deploy a java application using sdk-java using the AWS ALB as the target. Create at least one worker.
  4. Observe that polling for tasks logs these exceptions, and the frequency of the exceptions scales inversely with the value of the ALB idle-timeout.

## Specifications

  - Version: 1.1.0
  - Platform: Java 11

Note that I debugged into the exceptions and can observe them coming out of the GRPC layer and bubbling up to the Poller's error handler, which is treating all errors in the same manner. Probably this error could be recognized as harmless and logged at a lower logging level?

**Comment by vitarb** [comment]
I've tried to reproduce this and the only exception that I see logged is at WARN level from the [grpc retrier](https://github.com/temporalio/sdk-java/blob/0da3149c8eb16454c30fb7bda32d28f2539f3f3c/temporal-serviceclient/src/main/java/io/temporal/internal/retryer/GrpcSyncRetryer.java#L56). I don't see anything logged at the ERROR level.
Are you saying that you would prefer to have all gRPC exceptions being logged at a lower level (INFO/DEBUG), or is WARN sufficient?
I think that WARN is a reasonable default value, but we can discuss making it configurable via RpcRetryOptions.

**Comment by vitarb** [comment]
Is something along the lines of #737 would be useful to you?

**Comment by vitarb** [comment]
I made a change that allows making log level for rpc retries configurable, but I don't like this approach as it restricts us to a single level in the entire retry layer, so we are not going to land this change. Instead I'm going to adjust the default log level from WARN to DEBUG for they sync retrier.

**Comment by josh-berry** [comment]
Should already be addressed as part of other work; closing.
