### ISSUE TITLE
Opentracing: "UnsupportedFormatException: Builtin.TEXT_MAP_INJECT" with Jaeger tracer

### ISSUE THREAD

**Issue by tsurdilo** [temporalio/sdk-java#621]
Trying out to use Java SDK OpenTracing support with Jaeger client:

1. Add Jaeger client as depend:

           implementation group: 'io.jaegertracing', name: 'jaeger-client', version: '1.6.0'

2. Create a Tracer:

        JaegerTracer tracer =
        new Configuration("temporal-app")
          .withReporter(
              new Configuration.ReporterConfiguration()
                  .withSender(
                      new Configuration.SenderConfiguration()
                          .withEndpoint("http://localhost:14268/api/traces")))
          .withCodec(
              new Configuration.CodecConfiguration()
                  .withCodec(Format.Builtin.TEXT_MAP_INJECT, new TextMapCodec(false)))
          .getTracer();

(the .withCodec seems to do absolutely nothing, so can be removed in test even)

3. Set the tracer in OpenTracingOptions

Try tracing, you should get:
    
  Caused by: io.jaegertracing.internal.exceptions.UnsupportedFormatException: Builtin.TEXT_MAP_EXTRACT

## Specifications

  - Version: 1.1.0
  - Platform:

Note - to add Jaeger to your local docker compose yaml you can just add:

     jaeger:
     image: jaegertracing/all-in-one:latest
     ports:
       - "5775:5775/udp"
       - "6831:6831/udp"
       - "6832:6832/udp"
       - "5778:5778"
       - "16686:16686"
       - "14268:14268"
       - "9411:9411"

in the services section

**Comment by tsurdilo** [comment]
For a simple test just import the jaeger client lib (depends) and create a tracer with:

     Reporter reporter = new InMemoryReporter();
      Sampler sampler = new ConstSampler(true);
      Tracer tracer = new JaegerTracer.Builder("temporal-test")
              .withReporter(reporter)
              .withSampler(sampler)
              .build();
      GlobalTracer.registerIfAbsent(tracer);

**Comment by Spikhalskiy** [comment]
It looks like Jaeger OpenTracing java client doesn't support TEXT_MAP_INJECT and TEXT_MAP_EXTRACT strategies. I filed an issue regarding that into Jaeger java client repo: https://github.com/jaegertracing/jaeger-client-java/issues/789
Taking into account that Jaeger is a major OpenTracing/OpenTelementry solution, I implemented a workaround in temporal for this issue until it's addressed in Jaeger client: https://github.com/temporalio/sdk-java/pull/624

**Comment by Spikhalskiy** [comment]
Closed by #624
