### ISSUE TITLE
Upsert memo support

### ISSUE THREAD

**Issue by vkoby** [temporalio/sdk-java#623]
Memo can be utilized by users as an "additional" workflow result that is not explicitly populated in the workflow result object.
Workflow Executions should have an ability to modify/upsert the memo during the execution, not just at the start time.
There is a `ModifyWorkflowPropertiesCommandAttributes` command in place for this already.

**Comment by aleskovets** [comment]
Sad that java sdk does not have it. Great feature to optimize number of requests with advanced visibility
