### ISSUE TITLE
Add support for MaxConcurrentActivityExecutionSize for async activities

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#70]
Customer reported:

`We are noticing that .setMaxConcurrentWorkflowExecutionSize(2) and  .setMaxConcurrentActivityExecutionSize(2) on WorkerOptions don’t seem to work if we do asynchronous activity completion. Have you guys experienced this/have a good way around this? We use the async activity completion to be able to use Kotlin coroutines in parts of our code. I am trying to get some logs from the team that reported it, but wanted to see if you guys had seen something similar`

The proposed solution is to have a special API for async activity completion from the same process, which is different from the current API which was intended for completion from any process. This new API would perform counting correctly.

**Comment by vitarb** [comment]
Make sure that when we implement https://github.com/temporalio/sdk-java/issues/14 we obey the limit set here.

**Comment by vitarb** [comment]
I don't think that MaxConcurrentActivityExecutionSize should limit the number of async activities as this defeats the point of running code async in the first place. We should consider introducing a new limit, confusing part about it is that it will only apply for async activities that must be completed in the same process vs those that use completion client from elsewhere.

**Comment by vitarb** [comment]
Resolved in https://github.com/temporalio/sdk-java/pull/291
