### ISSUE TITLE
TEMPORAL_DEBUG flag is ignored by deadlock detector in eventLoop 

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#724]
Bug report:
https://community.temporal.io/t/testing-temporal-workflows/2918/4

`SyncWorkflow#eventLoop` lacks a check for `TEMPORAL_DEBUG` flag

**Comment by nkatre** [comment]
Thanks for fixing this @Spikhalskiy Is there an approximate ETA when the fix would be released ?

**Comment by Spikhalskiy** [comment]
@nkatre We just recently released, so the next release will be in about a month. You can use our snapshot builds if you don't have your own fork/don't want to build your own artifacts.
