### ISSUE TITLE
Provide shaded release JAR

### ISSUE THREAD

**Issue by mfateev** [temporalio/sdk-java#75]
From slack:

> I am exploring temporal as a replacement for our internal workflow engine.
> Is there a java uber-jar available with all dependencies shaded to an internal namespace? I see a lot of netty & guava dependencies and if I make a REST call in an activity using a library dependent on a different version of netty, the classes could conflict, right?

So I propose to add the shaded jar to the release artifacts

**Comment by Spikhalskiy** [comment]
Closed by #1656
