### ISSUE TITLE
AuthorizationGrpcMetadataProvider doesn't have a public constructor

### ISSUE THREAD

**Issue by jrpedrianes** [temporalio/sdk-java#762]
## Expected Behavior
Allow to instantiate AuthorizationGrpcMetadataProvider

## Actual Behavior
We can't create an AuthorizationGrpcMetadataProvider instance without using the same package.

## Specifications

  - Version: 1.3.1
  - Platform: sdk-java

**Comment by Spikhalskiy** [comment]
I will fix it in 1.4.0
You know how you can work around this for now, right?
