### ISSUE TITLE
[Port] Allow multiple host:port to be specified for connection

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#815]
JavaSDK should have this change from Go SDK incorporated: https://github.com/temporalio/sdk-go/pull/582
An original description from Go SDK request (https://github.com/temporalio/sdk-go/issues/577):

### Distribute pollers to multiple frontend servers.

**Is your feature request related to a problem? Please describe.**
When worker configured to have multiple pollers, all pollers share one connection and will poll from only one frontend server. This does not work well when worker count is the same or smaller than frontend server count.

**Describe the solution you'd like**
There should have an option to be able to specify how many connections you want for one worker so the load is more evenly distributed among frontend servers. 

**Describe alternatives you've considered**
User has to start more workers to have the load more evenly distributed across all frontend servers.

**Comment by Quinn-With-Two-Ns** [comment]
Closing as original Go PR was closed in favour of DNS based approach
