### ISSUE TITLE
Expose health check on WorkflowServiceStubs or WorkflowClient

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#828]
Temporal SDK should expose a method like `WorkflowServiceStubs#healthCheck` or `WorkflowServiceStubs#isHealthy` that allows users to check if the WorkflowClient/WorkflowServiceStubs underlying channel / connection to Temporal server is healthy.
There were quite a bit of user requests for such a method from users for all SDKs.
Having this method on Stubs is preferable over WorkflowClient, because it's the lowest level abstraction on top of the channel and WorkflowClient can just fall back on the WorkflowServiceStubs method. But if the language doesn't have a wrapper for stubs (like Java does), this method may be on WorkflowClient.

Issues for other SDKs:
https://github.com/temporalio/sdk-go/issues/595
https://github.com/temporalio/sdk-node/issues/312

**Comment by cretz** [comment]
@Spikhalskiy - Will wait on suggested Java signatures before adding to Go.

To confirm, are you thinking `healthCheck` just invokes https://github.com/grpc/grpc/blob/790ce5c97ff3a3922d50a1fd3a4bab91e2bcd435/src/proto/grpc/health/v1/health.proto#L45 for the workflow service, and then returns a boolean? And `isHealthy` returns the boolean based on the client's existing known knowledge (i.e. last health check, not a new one)? We can definitely do both easily in Go.
