### ISSUE TITLE
Workflow search queries APIs

### ISSUE THREAD

**Issue by akdoan1** [temporalio/sdk-java#835]
**Describe the solution you'd like**
* I would like to use the Java SDK to query [elasticsearch] for open workflow executions like in Go: https://pkg.go.dev/go.temporal.io/sdk/client#Client.ListOpenWorkflow.
* I'm sure that other workflow search queries would be useful here too. 

**Describe alternatives you've considered**
* query elasticsearch directly

**Additional context**

---

Edit: Apologies, found updates right after posting: https://github.com/temporalio/samples-java/blob/16982c43266d4ae3abfa7009fb3a188d1fa11c1a/src/test/java/io/temporal/samples/listworkflows/ListWorkflowsTest.java

**Comment by Quinn-With-Two-Ns** [comment]
Closing as duplicate https://github.com/temporalio/sdk-java/issues/1552
