### ISSUE TITLE
Worker doesn't log failure during sending workflow task completion request

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#900]
## Actual Behavior

A worker already logs when Workflow Task Processing fails with an unexpected exception.
But if reporting of the workflow task result to the server fails, the worker log is silent.
At the same time, both situations reach `UncaughtExceptionHandler` in the same manner.

## Expected Behavior

If a worker logs a problem during workflow task processing, the worker should log a problem during reporting the workflow task processing result to the server. Especially because it potentially can be related to misformed commands.

## Steps to Reproduce the Problem

Create an invalid Command (for example, schedule an activity with invalid retry parameters).
`WorkflowWorker.TaskHandlerImpl#handle` gets an `INVALID_ARGUMENT` exception from the server inside `sendReply`.
Worker log is clean and doesn't show the issue anyhow.

## Notes

There is also a related problem that because `WorkflowWorker.TaskHandlerImpl#handle/sendReply` happens outside of WorkflowTaskHandler, exception there doesn't lead to a workflow thread destroy and cache invalidation, while it should. This points out that a larger refactoring here may be needed to keep things clean and easy to maintain.

**Comment by akdoan1** [comment]
I'm assuming that the worker's reporting of the task processing result a blocking/synchronous call to the server. I don't think there are any metrics around interaction between the worker and the server based on the list in [workflow metrics](https://github.com/temporalio/sdk-java/blob/3deccf2c50b1bdb9f41cd2b385ee4dce402acf82/temporal-sdk/src/main/java/io/temporal/internal/metrics/MetricsType.java#L48). 

Can we add metrics to indicate success/failure and latency of this reporting call?

**Comment by Spikhalskiy** [comment]
@akdoan1 There is `failed_workflow_tasks` metric on the Temporal server to monitor the volume of failed workflow tasks.
I don't think we are going to implement metrics reporting pure server return codes. Our SDK metrics are formulated around concepts that make sense from "business logic" level. Workflows, Workflow tasks, Activities and their executions. 

If you really want that, we expose WorkflowServiceStubsOptions#grpcClientInterceptors.
