### ISSUE TITLE
Can't register activity implementation that uses inheritance

### ISSUE THREAD

**Issue by aniketbhatnagar** [temporalio/sdk-java#929]
## Expected Behavior
Consider the following:
```
@ActivityInterface
public interface BlockListenerActivities {
     @ActivityMethod
     Optional<BlockRef> processNextBlock();
}

@Slf4j
public abstract class BaseBlockListenerActivities implements BlockListenerActivities {
    @Override
    public final Optional<BlockRef> processNextBlock() {
        return doProcessNextBlock();
    }

    abstract protected Optional<BlockRef> doProcessNextBlock();
}

@Slf4j
public class BlockListenerActivitiesImpl extends BaseBlockListenerActivities {
    @Override
    protected Optional<BlockRef> doProcessNextBlock() {
        log.info("Processing next ETH block");
        return Optional.empty();
    }
}
```

Then, registering the activity implementation (`worker.registerActivitiesImplementations(new BlockListenerActivitiesImpl());`) should work.

## Actual Behavior
Registering the activity implementation (`worker.registerActivitiesImplementations(new BlockListenerActivitiesImpl());`) causes the exception `Class doesn't implement any non empty interface annotated with @ActivityInterface: BlockListenerActivitiesImpl`.

It seems that that SDK expects `BlockListenerActivitiesImpl` to explicitly say `implements BlockListenerActivities`. 

I ran into this is because I was provided a "quarkus" injected bean that automatically extends the activity implementation class to form a proxy like `ActivityImpl_ClientProxy extends ActivityImpl` and temporal SDK rejects `ActivityImpl_ClientProxy` as a valid activity implementation.

## Steps to Reproduce the Problem
Use the code snippet above and register activity using `worker.registerActivitiesImplementations(new BlockListenerActivitiesImpl());`

## Specifications

  - Version: temporal-sdk 1.6.0
  - Platform: Reproduced on Mac with jdk 14 but should be applicable on all platforms.

**Comment by tsurdilo** [comment]
Community Forum ref: https://community.temporal.io/t/cant-register-activity-implementation-that-uses-inheritance/3603
