### ISSUE TITLE
Header support for signals and queries

### ISSUE THREAD

**Issue by cretz** [temporalio/sdk-java#940]
**Is your feature request related to a problem? Please describe.**

Headers were added to signals and queries in https://github.com/temporalio/temporal/pull/2149. 

**Describe the solution you'd like**

Add to SDK

**Additional context**

* Go SDK: https://github.com/temporalio/sdk-go/pull/631
* TypeScript SDK: https://github.com/temporalio/sdk-typescript/issues/438

**Comment by Spikhalskiy** [comment]
@pooja-fyndna We don’t provide time estimates for feature requests. When there is work done - there would be linked PRs, so there was no updates.
We gladly accept contributions.

**Comment by bhagya05** [comment]
@Spikhalskiy We are extending WorkflowClientCallsInterceptorBase and OpenTracingWorkflowInboundCallsInterceptor
to add tracing for signal in temporal 1.25.1 java sdk.
Is this a valid approach ?

**Comment by Quinn-With-Two-Ns** [comment]
This issue was already resolved by https://github.com/temporalio/sdk-java/pull/1819
