### ISSUE TITLE
Opentelemetry tracing support for java 

### ISSUE THREAD

**Issue by sidhu-sb** [temporalio/sdk-java#950]
can you provide an example of how to use opentelemetry tracing in temporal.

Go-SDK has an otel tracing interceptor so was looking for something similar in java.

**Comment by Spikhalskiy** [comment]
Here is a configuration for opentracing:
https://github.com/temporalio/sdk-java/tree/master/temporal-opentracing#usage
here is how is can be used with opentelemetry:
https://github.com/temporalio/sdk-java/tree/master/temporal-opentracing#opentelemetry

Please use Temporal 
forum: https://community.temporal.io/
slack: https://temporalio.slack.com/join/shared_invite/zt-onhti57l-J0bl~Tr7MqSUnIc1upjRkw#/shared-invite/email
or StackOverflow: https://stackoverflow.com/questions/tagged/temporal-workflow
for questions.

You can find me as @Dmtiry in the company's Slack.

**Comment by tsurdilo** [comment]
Java samples issue: https://github.com/temporalio/samples-java/issues/207
