### ISSUE TITLE
Expose a method allowing user code to defined if they are inside workflow thread

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#955]
**Is your feature request related to a problem? Please describe.**
Users want to reuse pieces of code in workflow and outside of the workflow context and use deterministic `Workflow` class methods if they are inside a workflow context and non-deterministic versions if they are outside.

**Describe the solution you'd like**
Probably a method on the `Workflow` class returning true if we are executing inside a workflow thread

**Describe alternatives you've considered**
- Not exposing access to this info, maybe enforcing users to don't share code in such a manner.
- Give an API, but not on `Workflow`, but somewhere deeper, which will highlight the fact that it may be not a good practice.

**Additional context**
Related discussion in a Temporal Support Slack: https://temporalio.slack.com/archives/CTT84KXK9/p1641489380001200

**Comment by mfateev** [comment]
I have no objections having that we document the intended purpose well.
