### ISSUE TITLE
Static and synthetic methods are considered Activity methods in activity interfaces

### ISSUE THREAD

**Issue by WellingR** [temporalio/sdk-java#977]
## Expected Behavior
While running a jacoco coverage run on my temporal project. I discovered that temporal tries to register activity types for generated (synthetic) methods.

I would expect that running with or without jacoco has no influcence on the result of the test itself.

Jacoco generates the following method with is both static and synthetic (can be seen using reflection: `Method::isSynthetic()`
`private static boolean[] com.mypackage.GreetingActivities.$jacocoInit(java.lang.invoke.MethodHandles$Lookup,java.lang.String,java.lang.Class)`

The java spec states:
> A construct emitted by a Java compiler must be marked as synthetic if it does not correspond to a construct declared explicitly or implicitly in source code, unless the emitted construct is a class initialization method 

To me it would make sense for temporal to ignore synthetic methods. As well as static methods.

## Actual Behavior

```
java.lang.IllegalArgumentException: "$jacocoInit" activity type is already registered with the worker
	at io.temporal.internal.activity.POJOActivityTaskHandler.registerActivityImplementation(POJOActivityTaskHandler.java:140)
	at io.temporal.internal.activity.POJOActivityTaskHandler.registerActivityImplementations(POJOActivityTaskHandler.java:93)
	at io.temporal.internal.sync.SyncActivityWorker.registerActivityImplementations(SyncActivityWorker.java:91)
	at io.temporal.worker.Worker.registerActivitiesImplementations(Worker.java:313)
```

## Steps to Reproduce the Problem

Change `HelloActivity` in the temporal java samples as follows:

Ensure there are two activity interfaces declared, which both have a static methods:
```java
  @ActivityInterface
  public interface GreetingActivities {

    @ActivityMethod
    String composeGreeting(String greeting, String name);

    static String name() {
      return "1";
    }
  }

  @ActivityInterface
  public interface GreetingActivities2 {

    @ActivityMethod
    String composeGreeting2(String greeting, String name);

    static String name() {
      return "2";
    }
  }
```
Ensure that both interfaces are implemented (GreetingActivities already has an implementation)
```java
  static class GreetingActivitiesImpl2 implements GreetingActivities2 {
    @Override
    public String composeGreeting2(String greeting, String name) {
      return greeting + " " + name + "!";
    }
  }
```
In the first test in `HelloActivityTest`, ensure that both activity implementaitons are registered
```java
    testWorkflowRule
        .getWorker()
        .registerActivitiesImplementations(
            new GreetingActivitiesImpl(), new HelloActivity.GreetingActivitiesImpl2());
```

Enable jacoco in build.gradle.
```
plugins {
    ... (existing plugins here) ...
    id 'jacoco'
}

jacocoTestReport {
    dependsOn test // tests are required to run before generating the report
}

jacoco {
    toolVersion = "0.8.7"
    reportsDir = file("$buildDir/jacoco")
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport // report is always generated after tests run
}
```

Then run `  ./gradlew clean  jacocoTestReport`

## Specifications

  - Version: The samples used temporal-sdk 1.7.0
  - Platform: MacOs (Monerey M1), reproduced using both JDK 11 and 17

**Comment by mfateev** [comment]
An activity interface defines the signature of remote calls. Having static methods in this interface doesn't really make sense as the caller workflow and an activity implementation can reside in completely different codebases and processes.
