### ISSUE TITLE
Make WorkflowServiceStubsOptions#rpcLongPollTimeout configurable

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/sdk-java#988]
**Is your feature request related to a problem? Please describe.**

Right now WorkflowServiceStubsOptions#rpcLongPollTimeout has to be 70s or more because Server's default timeout is 60s.
It looks like now Server uses a timeout from the client that initiates the long poll to return the result (empty or non-empty) in time. And 60s is just a cap for this timeout.

> Yimin Chen 
> To be clear, if the context timeout on the connection is less than 60s, server would return empty response before timeout hit.
> there is a small gap server added to make sure the empty response is delivered before actual context timeout when it is less than 60s.
> 

Not allowing users to configure the long polls to be shorter than 70s, Temporal makes configuration tricky for some of the users who may be using middle layers with a strict configuration (like reverse proxies) that may limit the durtion of long polls.

**Describe the solution you'd like**
Taking into account that the Server takes a time limit from the request timeout/deadline to return a response in an amount of time shorter than 60s, we can allow an SDK to accept rpcLongPollTimeout values less than the 70s. that and returns a response in a shorter amount of time.

GoSDK: https://github.com/temporalio/sdk-go/issues/705

**Comment by mfateev** [comment]
I don't think we want to rely on gRPC timeout for long polls. The service returns OK with an empty result after 60 seconds. The timeout cuts the client request while the service is still waiting on the long poll. 

We could change the service to return a long poll a few hundred milliseconds before the timeout, but it is not as simple as allowing configuration of the timeout by the client.
