### ISSUE TITLE
Retry Interval doesn't work for LocalActivity, default value is used instead

### ISSUE THREAD

**Issue by GeekNickson** [temporalio/sdk-java#989]
Retry interval doesn't work for LocalActivity. 
The problem is that in LocalActivityWorker.class there is a method "handleLocalActivity", which sets retryPolicy.
in line 255 there is a check:
`if (retryPolicy.getMaximumInterval().getNanos() > 0) {
        roBuilder.setMaximumInterval(
            ProtobufTimeUtils.toJavaDuration(retryPolicy.getMaximumInterval()));
}`

The problem is that getNanos() always returns 0, so default value is used. It doesn't matter if use MethodRetry annotation or specify RetryOptions via setRetryOptions method of LocalActivityOptions. (I do specify nanos in Duration.ofSeconds(30, 1) like so)

## Specifications

  - Version: 1.7.1
  - Platform: 1.7.1

**Comment by Spikhalskiy** [comment]
Confirm. Thanks for the report!
